/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: tEVJpKmZgCv_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: bUjxyyacyjDo/component
import Footermenu from "../../Footermenu"; // plasmic-import: puYfivG4HZSi/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../www_offtoglow_com/plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicFaq.module.css"; // plasmic-import: tEVJpKmZgCv_/css

import CheckSvgIcon from "../www_offtoglow_com/icons/PlasmicIcon__CheckSvg"; // plasmic-import: v7iefsRDFFri/icon
import Icon4Icon from "../www_offtoglow_com/icons/PlasmicIcon__Icon4"; // plasmic-import: 4-aZVVDUZLRE/icon

createPlasmicElementProxy;

export type PlasmicFaq__VariantMembers = {};
export type PlasmicFaq__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaq__VariantsArgs;
export const PlasmicFaq__VariantProps = new Array<VariantPropType>();

export type PlasmicFaq__ArgsType = {};
type ArgPropType = keyof PlasmicFaq__ArgsType;
export const PlasmicFaq__ArgProps = new Array<ArgPropType>();

export type PlasmicFaq__OverridesType = {
  root?: Flex__<"div">;
  navigation?: Flex__<"div">;
  scrollNav?: Flex__<"div">;
  h1?: Flex__<"h1">;
  h4?: Flex__<"h4">;
  h3?: Flex__<"h3">;
  footermenu?: Flex__<typeof Footermenu>;
};

export interface DefaultFaqProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFaq__RenderFunc(props: {
  variants: PlasmicFaq__VariantsArgs;
  args: PlasmicFaq__ArgsType;
  overrides: PlasmicFaq__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isDefaultNav",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicFaq.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicFaq.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicFaq.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          styleTokensClassNames_antd_5_hostless,
          styleTokensClassNames_plasmic_rich_components,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"navigation"}
          data-plasmic-override={overrides.navigation}
          className={classNames(projectcss.all, sty.navigation)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__sXqdG)}
            displayHeight={"32px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/about_offtoglow_com/images/logo2025Svg.svg",
              fullWidth: 4543,
              fullHeight: 880,
              aspectRatio: undefined
            }}
          />

          <div className={classNames(projectcss.all, sty.freeBox__kqkR9)} />

          <div className={classNames(projectcss.all, sty.freeBox___8Y90K)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ykGzG
              )}
            >
              {"Login: "}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__yVUcP
              )}
              component={Link}
              href={"https://talent.offtoglow.com/"}
              platform={"nextjs"}
              target={"_blank"}
            >
              {"Talent"}
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kc6Jl
              )}
            >
              {"|"}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__xXcG1
              )}
              component={Link}
              href={"https://booker.offtoglow.com/"}
              platform={"nextjs"}
              target={"_blank"}
            >
              {"Booker"}
            </PlasmicLink__>
          </div>
          {false ? (
            <div className={classNames(projectcss.all, sty.freeBox__ecYg2)}>
              <Button
                className={classNames("__wab_instance", sty.button__oQoic)}
                color={"white"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToPage"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: (() => {
                            try {
                              return "https://talent.offtoglow.com/login";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToPage"] != null &&
                    typeof $steps["goToPage"] === "object" &&
                    typeof $steps["goToPage"].then === "function"
                  ) {
                    $steps["goToPage"] = await $steps["goToPage"];
                  }
                }}
                selectLeft={true}
                shape={"rounded"}
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Ayc
                  )}
                >
                  {"Talent Sign In"}
                </div>
              </Button>
              <Button
                className={classNames("__wab_instance", sty.button__xS8Ys)}
                color={"white"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToPage"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: (() => {
                            try {
                              return "https://booker.offtoglow.com/login";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToPage"] != null &&
                    typeof $steps["goToPage"] === "object" &&
                    typeof $steps["goToPage"].then === "function"
                  ) {
                    $steps["goToPage"] = await $steps["goToPage"];
                  }
                }}
                selectRight={true}
                shape={"rounded"}
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d7ZvX
                  )}
                >
                  {"Booker Sign In"}
                </div>
              </Button>
            </div>
          ) : null}
          <Button
            className={classNames("__wab_instance", sty.button___34Dsg)}
            color={"green"}
            onClick={async event => {
              const $steps = {};

              $steps["goToRegister"] = true
                ? (() => {
                    const actionArgs = { destination: `/register` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToRegister"] != null &&
                typeof $steps["goToRegister"] === "object" &&
                typeof $steps["goToRegister"].then === "function"
              ) {
                $steps["goToRegister"] = await $steps["goToRegister"];
              }
            }}
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7LavC
              )}
            >
              {"Join for Free"}
            </div>
          </Button>
        </div>
        <div
          data-plasmic-name={"scrollNav"}
          data-plasmic-override={overrides.scrollNav}
          className={classNames(projectcss.all, sty.scrollNav)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__rwkm)}
            displayHeight={"32px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/about_offtoglow_com/images/otGlogobeta2Svg.svg",
              fullWidth: 4543,
              fullHeight: 880,
              aspectRatio: undefined
            }}
          />

          <div className={classNames(projectcss.all, sty.freeBox__yf2Up)} />

          <div className={classNames(projectcss.all, sty.freeBox__vw57N)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__w4ZuQ
              )}
            >
              {"Login: "}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__bnOvC
              )}
              component={Link}
              href={"https://talent.offtoglow.com/"}
              platform={"nextjs"}
              target={"_blank"}
            >
              {"Talent"}
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pvc7
              )}
            >
              {"|"}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link___8NYyP
              )}
              component={Link}
              href={"https://booker.offtoglow.com/"}
              platform={"nextjs"}
              target={"_blank"}
            >
              {"Booker"}
            </PlasmicLink__>
          </div>
          {false ? (
            <div className={classNames(projectcss.all, sty.freeBox__aBEj4)}>
              <Button
                className={classNames("__wab_instance", sty.button__gdHk)}
                color={"white"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToPage"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: (() => {
                            try {
                              return "https://talent.offtoglow.com/login";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToPage"] != null &&
                    typeof $steps["goToPage"] === "object" &&
                    typeof $steps["goToPage"].then === "function"
                  ) {
                    $steps["goToPage"] = await $steps["goToPage"];
                  }
                }}
                selectLeft={true}
                shape={"rounded"}
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oFer
                  )}
                >
                  {"Talent Sign In"}
                </div>
              </Button>
              <Button
                className={classNames("__wab_instance", sty.button__tfqH)}
                color={"white"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToPage"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: (() => {
                            try {
                              return "https://booker.offtoglow.com/login";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToPage"] != null &&
                    typeof $steps["goToPage"] === "object" &&
                    typeof $steps["goToPage"].then === "function"
                  ) {
                    $steps["goToPage"] = await $steps["goToPage"];
                  }
                }}
                selectRight={true}
                shape={"rounded"}
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__afBJa
                  )}
                >
                  {"Booker Sign In"}
                </div>
              </Button>
            </div>
          ) : null}
          <Button
            className={classNames("__wab_instance", sty.button__q0FcS)}
            color={"green"}
            onClick={async event => {
              const $steps = {};

              $steps["goToRegister"] = true
                ? (() => {
                    const actionArgs = { destination: `/register` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToRegister"] != null &&
                typeof $steps["goToRegister"] === "object" &&
                typeof $steps["goToRegister"].then === "function"
              ) {
                $steps["goToRegister"] = await $steps["goToRegister"];
              }
            }}
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ovCy
              )}
            >
              {"Join for Free"}
            </div>
          </Button>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__m3AiE)}>
          <div className={classNames(projectcss.all, sty.freeBox__f0G4E)}>
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"FAQ"}
            </h1>
            <h4
              data-plasmic-name={"h4"}
              data-plasmic-override={overrides.h4}
              className={classNames(
                projectcss.all,
                projectcss.h4,
                projectcss.__wab_text,
                sty.h4
              )}
            >
              {
                "At OfftoGlow, we believe a personal brand is more than presence\u2014it\u2019s potential. Our mission is to help personal brands unlock that potential by turning visibility into revenue, faster and smarter."
              }
            </h4>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___1ZywP)}>
            <h3
              data-plasmic-name={"h3"}
              data-plasmic-override={overrides.h3}
              className={classNames(
                projectcss.all,
                projectcss.h3,
                projectcss.__wab_text,
                sty.h3
              )}
            >
              {"Our Story"}
            </h3>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qgQa6
              )}
            >
              {
                "After nearly 15 years in the entertainment industry, our founder saw the same challenge everywhere: talented individuals building strong audiences, but struggling to monetize their brand beyond a few channels. OfftoGlow was created to change that\u2014by giving personal brands the tools to scale their income as easily as they grow their influence."
              }
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__mrgpL)}>
            <div className={classNames(projectcss.all, sty.freeBox__pcaNw)}>
              <div className={classNames(projectcss.all, sty.freeBox___9QXxj)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__fIpd
                  )}
                >
                  {"Why OfftoGlow"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g0UYf
                  )}
                >
                  {
                    "We\u2019re building the world\u2019s first Global Personal Brand Technology Platform. Starting with bookings, OfftoGlow helps personal brands secure deals more efficiently. From there, we\u2019re expanding step by step\u2014into merchandise (with production and delivery handled end-to-end), digital products, fan subscriptions, events, and more. These are just the beginning: our vision is a platform where every part of a personal brand\u2019s growth and monetization can be managed in one place."
                  }
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___8Zspl)}>
              <div className={classNames(projectcss.all, sty.freeBox__rF4Ls)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__sfh8T
                  )}
                >
                  {"Our vision"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sEgZq
                  )}
                >
                  {
                    "We envision a world where every personal brand can grow into a meaningful, future-proof brand\u2014supported, monetized, and managed all in one place."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rN6E0)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__zUwm2
                  )}
                >
                  {"Our Mission"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rYzgF
                  )}
                >
                  {
                    "To empower every personal brand with enterprise-grade monetization tools made simple, giving them the means to scale income, build stronger partnerships, launch new ventures, and grow into sustainable, future-proof brands."
                  }
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cjCz)}>
              <div className={classNames(projectcss.all, sty.freeBox__hb3Gn)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__weqQ
                  )}
                >
                  {"In Beta\u2014Shaped by Personal Brands"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nf72
                  )}
                >
                  {
                    "Today, we\u2019re collaborating with a small group of early adopters\u2014artists, coaches, hosts, and more\u2014to refine OfftoGlow. Their feedback is shaping the platform from day one, ensuring we address real monetization challenges for personal brands."
                  }
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ppGZd)}>
            <div className={classNames(projectcss.all, sty.freeBox__d0WG2)}>
              <div className={classNames(projectcss.all, sty.freeBox__akgZ0)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__wcdB9
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-85NLt28mNxmq)" }}
                    >
                      {" Ready to grow your "}
                    </span>
                  </React.Fragment>
                </h2>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__uxxz9
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#F15A24" }}
                    >
                      {"Personal Brand income?"}
                    </span>
                  </React.Fragment>
                </h2>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o7Il9
                )}
              >
                {
                  "Be part of our beta and help define the future of personal brand monetization, guided by a team of seasoned experts across the industry."
                }
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__yv5ZN)}>
            <div className={classNames(projectcss.all, sty.freeBox__p2Cc2)}>
              <div className={classNames(projectcss.all, sty.freeBox___8ND)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___49Kre)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"168px"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/about_offtoglow_com/images/otGlogobeta2Svg.svg",
                    fullWidth: 4543,
                    fullHeight: 880,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aXdme
                  )}
                >
                  {
                    "OfftoGlow is the world\u2019s first platform of its kind \u2014 a Global Personal Brand Technology Platform built to empower creators, entrepreneurs, and influencers to unlock their full earning potential. By combining cutting-edge tools, seamless infrastructure, and data-driven insights, we enable personal brands to grow, monetize, and thrive on a truly global scale. With OfftoGlow, personal brands gain the intelligence, infrastructure, and autonomy they need to transform influence into sustainable impact."
                  }
                </div>
              </div>
              <Footermenu
                data-plasmic-name={"footermenu"}
                data-plasmic-override={overrides.footermenu}
                className={classNames("__wab_instance", sty.footermenu)}
              />
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8OeZ
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      "© " +
                      new Date().getFullYear() +
                      " OfftoGlow Ltd. All rights reserved."
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u00a9 2025 OfftoGlow Ltd. All rights reserved.";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navigation", "scrollNav", "h1", "h4", "h3", "footermenu"],
  navigation: ["navigation"],
  scrollNav: ["scrollNav"],
  h1: ["h1"],
  h4: ["h4"],
  h3: ["h3"],
  footermenu: ["footermenu"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigation: "div";
  scrollNav: "div";
  h1: "h1";
  h4: "h4";
  h3: "h3";
  footermenu: typeof Footermenu;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaq__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaq__VariantsArgs;
    args?: PlasmicFaq__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFaq__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFaq__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFaq__ArgProps,
          internalVariantPropNames: PlasmicFaq__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFaq__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaq";
  } else {
    func.displayName = `PlasmicFaq.${nodeName}`;
  }
  return func;
}

export const PlasmicFaq = Object.assign(
  // Top-level PlasmicFaq renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigation: makeNodeComponent("navigation"),
    scrollNav: makeNodeComponent("scrollNav"),
    h1: makeNodeComponent("h1"),
    h4: makeNodeComponent("h4"),
    h3: makeNodeComponent("h3"),
    footermenu: makeNodeComponent("footermenu"),

    // Metadata about props expected for PlasmicFaq
    internalVariantProps: PlasmicFaq__VariantProps,
    internalArgProps: PlasmicFaq__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "FAQ | OfftoGlow",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFaq;
/* prettier-ignore-end */
