/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: hsth_eFgD9oC

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Card from "../../Card"; // plasmic-import: twFopKdKGk6j/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "../www_offtoglow_com/plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicSucces.module.css"; // plasmic-import: hsth_eFgD9oC/css

createPlasmicElementProxy;

export type PlasmicSucces__VariantMembers = {};
export type PlasmicSucces__VariantsArgs = {};
type VariantPropType = keyof PlasmicSucces__VariantsArgs;
export const PlasmicSucces__VariantProps = new Array<VariantPropType>();

export type PlasmicSucces__ArgsType = {};
type ArgPropType = keyof PlasmicSucces__ArgsType;
export const PlasmicSucces__ArgProps = new Array<ArgPropType>();

export type PlasmicSucces__OverridesType = {
  root?: Flex__<"div">;
  card?: Flex__<typeof Card>;
  h2?: Flex__<"h2">;
  h3?: Flex__<"h3">;
  ul?: Flex__<"ul">;
};

export interface DefaultSuccesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSucces__RenderFunc(props: {
  variants: PlasmicSucces__VariantsArgs;
  args: PlasmicSucces__ArgsType;
  overrides: PlasmicSucces__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "email",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "firstStep",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return !$state.authForm.formSubmitted;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicSucces.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSucces.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSucces.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.root
        )}
      >
        <div className={classNames(projectcss.all, sty.freeBox__eNtm)}>
          <div className={classNames(projectcss.all, sty.freeBox__kijDv)}>
            <Card
              data-plasmic-name={"card"}
              data-plasmic-override={overrides.card}
              className={classNames("__wab_instance", sty.card)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__d3QYu
                )}
              >
                {"\u00a9 Colin Lloyd"}
              </div>
            </Card>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__oK2Zn)}>
            <div className={classNames(projectcss.all, sty.freeBox__avRQt)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zboYn
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h3
                            data-plasmic-name={"h3"}
                            data-plasmic-override={overrides.h3}
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3
                            )}
                          >
                            {"Thank You for Registering!"}
                          </h3>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h2>
                  }
                  <React.Fragment>
                    {
                      "We\u2019ve just sent a confirmation email to your email. To get started, simply check your inbox and click the verification link to activate your account.\n\n\ud83d\udd0d Can\u2019t find the email?\n\n"
                    }
                  </React.Fragment>
                  {
                    <ul
                      data-plasmic-name={"ul"}
                      data-plasmic-override={overrides.ul}
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__vfeic
                        )}
                      >
                        {
                          "Give it a few minutes\u2014it might still be on its way.\n"
                        }
                      </li>
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__zWiRh
                        )}
                      >
                        {
                          "Don\u2019t forget to peek into your spam or junk folder, just in case."
                        }
                      </li>
                    </ul>
                  }
                  <React.Fragment>
                    {
                      "\nIf you\u2019re still having trouble, feel free to reach out to us at support@offtoglow.com\u2014we\u2019re happy to help!\n\nWelcome aboard\u2014we\u2019re excited to have you! \ud83c\udf89"
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "card", "h2", "h3", "ul"],
  card: ["card"],
  h2: ["h2", "h3"],
  h3: ["h3"],
  ul: ["ul"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  card: typeof Card;
  h2: "h2";
  h3: "h3";
  ul: "ul";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSucces__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSucces__VariantsArgs;
    args?: PlasmicSucces__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSucces__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSucces__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSucces__ArgProps,
          internalVariantPropNames: PlasmicSucces__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSucces__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSucces";
  } else {
    func.displayName = `PlasmicSucces.${nodeName}`;
  }
  return func;
}

export const PlasmicSucces = Object.assign(
  // Top-level PlasmicSucces renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    card: makeNodeComponent("card"),
    h2: makeNodeComponent("h2"),
    h3: makeNodeComponent("h3"),
    ul: makeNodeComponent("ul"),

    // Metadata about props expected for PlasmicSucces
    internalVariantProps: PlasmicSucces__VariantProps,
    internalArgProps: PlasmicSucces__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Thank You for Registering | OfftoGlow",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSucces;
/* prettier-ignore-end */
