/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: 6XDVrmZWk_dH

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import UpdatePasswordForm from "../../UpdatePasswordForm"; // plasmic-import: E2Q3fYpTWWgF/component
import Card from "../../Card"; // plasmic-import: twFopKdKGk6j/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../www_offtoglow_com/plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicSetPassword.module.css"; // plasmic-import: 6XDVrmZWk_dH/css

createPlasmicElementProxy;

export type PlasmicSetPassword__VariantMembers = {};
export type PlasmicSetPassword__VariantsArgs = {};
type VariantPropType = keyof PlasmicSetPassword__VariantsArgs;
export const PlasmicSetPassword__VariantProps = new Array<VariantPropType>();

export type PlasmicSetPassword__ArgsType = {};
type ArgPropType = keyof PlasmicSetPassword__ArgsType;
export const PlasmicSetPassword__ArgProps = new Array<ArgPropType>();

export type PlasmicSetPassword__OverridesType = {
  root?: Flex__<"div">;
  updatePasswordForm?: Flex__<typeof UpdatePasswordForm>;
  card?: Flex__<typeof Card>;
  text?: Flex__<"div">;
};

export interface DefaultSetPasswordProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSetPassword__RenderFunc(props: {
  variants: PlasmicSetPassword__VariantsArgs;
  args: PlasmicSetPassword__ArgsType;
  overrides: PlasmicSetPassword__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicSetPassword.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSetPassword.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSetPassword.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          styleTokensClassNames_antd_5_hostless,
          styleTokensClassNames_plasmic_rich_components,
          sty.root
        )}
      >
        <div className={classNames(projectcss.all, sty.freeBox__zn9Fo)}>
          <div className={classNames(projectcss.all, sty.freeBox__mznCq)}>
            <UpdatePasswordForm
              data-plasmic-name={"updatePasswordForm"}
              data-plasmic-override={overrides.updatePasswordForm}
              className={classNames("__wab_instance", sty.updatePasswordForm)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__yg4Yc)}>
            <Card
              data-plasmic-name={"card"}
              data-plasmic-override={overrides.card}
              className={classNames("__wab_instance", sty.card)}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"\u00a9 Muneeb Syed"}
              </div>
            </Card>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "updatePasswordForm", "card", "text"],
  updatePasswordForm: ["updatePasswordForm"],
  card: ["card", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  updatePasswordForm: typeof UpdatePasswordForm;
  card: typeof Card;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSetPassword__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSetPassword__VariantsArgs;
    args?: PlasmicSetPassword__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSetPassword__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSetPassword__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSetPassword__ArgProps,
          internalVariantPropNames: PlasmicSetPassword__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSetPassword__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSetPassword";
  } else {
    func.displayName = `PlasmicSetPassword.${nodeName}`;
  }
  return func;
}

export const PlasmicSetPassword = Object.assign(
  // Top-level PlasmicSetPassword renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    updatePasswordForm: makeNodeComponent("updatePasswordForm"),
    card: makeNodeComponent("card"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicSetPassword
    internalVariantProps: PlasmicSetPassword__VariantProps,
    internalArgProps: PlasmicSetPassword__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Set Password || OfftoGlow",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSetPassword;
/* prettier-ignore-end */
