/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: 1g6hNjCxRGPz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: bUjxyyacyjDo/component
import Card from "../../Card"; // plasmic-import: twFopKdKGk6j/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../www_offtoglow_com/plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicChooseRole.module.css"; // plasmic-import: 1g6hNjCxRGPz/css

import CheckSvgIcon from "../www_offtoglow_com/icons/PlasmicIcon__CheckSvg"; // plasmic-import: v7iefsRDFFri/icon
import Icon4Icon from "../www_offtoglow_com/icons/PlasmicIcon__Icon4"; // plasmic-import: 4-aZVVDUZLRE/icon

createPlasmicElementProxy;

export type PlasmicChooseRole__VariantMembers = {};
export type PlasmicChooseRole__VariantsArgs = {};
type VariantPropType = keyof PlasmicChooseRole__VariantsArgs;
export const PlasmicChooseRole__VariantProps = new Array<VariantPropType>();

export type PlasmicChooseRole__ArgsType = {};
type ArgPropType = keyof PlasmicChooseRole__ArgsType;
export const PlasmicChooseRole__ArgProps = new Array<ArgPropType>();

export type PlasmicChooseRole__OverridesType = {
  root?: Flex__<"div">;
  h2?: Flex__<"h2">;
  card?: Flex__<typeof Card>;
};

export interface DefaultChooseRoleProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicChooseRole__RenderFunc(props: {
  variants: PlasmicChooseRole__VariantsArgs;
  args: PlasmicChooseRole__ArgsType;
  overrides: PlasmicChooseRole__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicChooseRole.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicChooseRole.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicChooseRole.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__bAoTs)}>
            <div className={classNames(projectcss.all, sty.freeBox__rqxXf)}>
              <div className={classNames(projectcss.all, sty.freeBox__e6Hjl)}>
                <h2
                  data-plasmic-name={"h2"}
                  data-plasmic-override={overrides.h2}
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2
                  )}
                >
                  {"Start Your Experience"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eCv9J
                  )}
                >
                  {
                    "Select your role to move forward. Join as a Talent to grow your presence, or as a Booker to find and collaborate with talent."
                  }
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__bVoy8)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__fExu1)}
                    color={"green"}
                    link={(() => {
                      try {
                        return "https://booker.offtoglow.com/login";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    target={true}
                  >
                    {"Booker"}
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__c7RUw)}
                    color={"blue"}
                    link={(() => {
                      try {
                        return "https://talent.offtoglow.com/login";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    target={true}
                  >
                    {"Talent"}
                  </Button>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__lnsR)}>
              <Card
                data-plasmic-name={"card"}
                data-plasmic-override={overrides.card}
                className={classNames("__wab_instance", sty.card)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ytQ8E
                  )}
                >
                  {"\u00a9 Graydon Driver"}
                </div>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2", "card"],
  h2: ["h2"],
  card: ["card"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h2: "h2";
  card: typeof Card;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChooseRole__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChooseRole__VariantsArgs;
    args?: PlasmicChooseRole__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChooseRole__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicChooseRole__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicChooseRole__ArgProps,
          internalVariantPropNames: PlasmicChooseRole__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicChooseRole__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChooseRole";
  } else {
    func.displayName = `PlasmicChooseRole.${nodeName}`;
  }
  return func;
}

export const PlasmicChooseRole = Object.assign(
  // Top-level PlasmicChooseRole renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),
    card: makeNodeComponent("card"),

    // Metadata about props expected for PlasmicChooseRole
    internalVariantProps: PlasmicChooseRole__VariantProps,
    internalArgProps: PlasmicChooseRole__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Choose Role | OfftoGlow",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicChooseRole;
/* prettier-ignore-end */
