/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: puYfivG4HZSi

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../www_offtoglow_com/plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicFootermenu.module.css"; // plasmic-import: puYfivG4HZSi/css

import InstagramIconSvgIcon from "./icons/PlasmicIcon__InstagramIconSvg"; // plasmic-import: 8IeaExDrxVer/icon

createPlasmicElementProxy;

export type PlasmicFootermenu__VariantMembers = {};
export type PlasmicFootermenu__VariantsArgs = {};
type VariantPropType = keyof PlasmicFootermenu__VariantsArgs;
export const PlasmicFootermenu__VariantProps = new Array<VariantPropType>();

export type PlasmicFootermenu__ArgsType = {};
type ArgPropType = keyof PlasmicFootermenu__ArgsType;
export const PlasmicFootermenu__ArgProps = new Array<ArgPropType>();

export type PlasmicFootermenu__OverridesType = {
  root?: Flex__<"div">;
  h6?: Flex__<"h6">;
  svg?: Flex__<"svg">;
};

export interface DefaultFootermenuProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFootermenu__RenderFunc(props: {
  variants: PlasmicFootermenu__VariantsArgs;
  args: PlasmicFootermenu__ArgsType;
  overrides: PlasmicFootermenu__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root
      )}
    >
      <PlasmicLink__
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.__wab_text,
          sty.link__eShrH
        )}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        {"Home"}
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.__wab_text,
          sty.link__tcAbm
        )}
        component={Link}
        href={"https://www.plasmic.app/"}
        platform={"nextjs"}
      >
        {"About Us"}
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.__wab_text,
          sty.link__gnyDk
        )}
        component={Link}
        href={"https://www.plasmic.app/"}
        platform={"nextjs"}
      >
        {"FAQ"}
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.__wab_text,
          sty.link__jFpB7
        )}
        component={Link}
        href={"https://www.plasmic.app/"}
        platform={"nextjs"}
      >
        {"Privacy Policy"}
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.__wab_text,
          sty.link__b4Qm
        )}
        component={Link}
        href={"https://www.plasmic.app/"}
        platform={"nextjs"}
      >
        {"Terms"}
      </PlasmicLink__>
      <div className={classNames(projectcss.all, sty.freeBox___2HdDs)}>
        <h6
          data-plasmic-name={"h6"}
          data-plasmic-override={overrides.h6}
          className={classNames(
            projectcss.all,
            projectcss.h6,
            projectcss.__wab_text,
            sty.h6
          )}
        >
          {"Follow Us"}
        </h6>
        <div className={classNames(projectcss.all, sty.freeBox__dgKRy)}>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__lmWcT
            )}
            component={Link}
            platform={"nextjs"}
          >
            <InstagramIconSvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />
          </PlasmicLink__>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h6", "svg"],
  h6: ["h6"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h6: "h6";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFootermenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFootermenu__VariantsArgs;
    args?: PlasmicFootermenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFootermenu__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFootermenu__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFootermenu__ArgProps,
          internalVariantPropNames: PlasmicFootermenu__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFootermenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFootermenu";
  } else {
    func.displayName = `PlasmicFootermenu.${nodeName}`;
  }
  return func;
}

export const PlasmicFootermenu = Object.assign(
  // Top-level PlasmicFootermenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h6: makeNodeComponent("h6"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicFootermenu
    internalVariantProps: PlasmicFootermenu__VariantProps,
    internalArgProps: PlasmicFootermenu__ArgProps
  }
);

export default PlasmicFootermenu;
/* prettier-ignore-end */
