/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: 3gtjCoHvk73C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Card from "../../Card"; // plasmic-import: twFopKdKGk6j/component
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query";
import { ConditionGuard } from "@plasmicpkgs/plasmic-basic-components";
import { EmailVerificationHandler } from "../../EmailVerificationHandler"; // plasmic-import: gRc82GluJ42g/codeComponent
import Button from "../../Button"; // plasmic-import: bUjxyyacyjDo/component

import { useScreenVariants as useScreenVariantshA1MVaLfOpX } from "../www_offtoglow_com/PlasmicGlobalVariant__Screen"; // plasmic-import: hA1mVaLfOP_X/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "../www_offtoglow_com/plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicVerifcation.module.css"; // plasmic-import: 3gtjCoHvk73C/css

import CheckSvgIcon from "../www_offtoglow_com/icons/PlasmicIcon__CheckSvg"; // plasmic-import: v7iefsRDFFri/icon
import Icon4Icon from "../www_offtoglow_com/icons/PlasmicIcon__Icon4"; // plasmic-import: 4-aZVVDUZLRE/icon

createPlasmicElementProxy;

export type PlasmicVerifcation__VariantMembers = {};
export type PlasmicVerifcation__VariantsArgs = {};
type VariantPropType = keyof PlasmicVerifcation__VariantsArgs;
export const PlasmicVerifcation__VariantProps = new Array<VariantPropType>();

export type PlasmicVerifcation__ArgsType = {};
type ArgPropType = keyof PlasmicVerifcation__ArgsType;
export const PlasmicVerifcation__ArgProps = new Array<ArgPropType>();

export type PlasmicVerifcation__OverridesType = {
  root?: Flex__<"div">;
  card?: Flex__<typeof Card>;
  graphQlFetcher?: Flex__<typeof GraphqlFetcher>;
  conditionGuard?: Flex__<typeof ConditionGuard>;
  emailVerificationHandler?: Flex__<typeof EmailVerificationHandler>;
  h2?: Flex__<"h2">;
  h3?: Flex__<"h3">;
  span?: Flex__<"span">;
};

export interface DefaultVerifcationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVerifcation__RenderFunc(props: {
  variants: PlasmicVerifcation__VariantsArgs;
  args: PlasmicVerifcation__ArgsType;
  overrides: PlasmicVerifcation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshA1MVaLfOpX()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicVerifcation.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicVerifcation.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicVerifcation.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__gvoaT)}>
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? false : true
            ) ? (
              <div className={classNames(projectcss.all, sty.freeBox___3JwVl)}>
                <Card
                  data-plasmic-name={"card"}
                  data-plasmic-override={overrides.card}
                  className={classNames("__wab_instance", sty.card)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lXxLx
                    )}
                  >
                    {"\u00a9 Spenser Sembrat"}
                  </div>
                </Card>
              </div>
            ) : null}
            <div className={classNames(projectcss.all, sty.freeBox__mImq)}>
              <GraphqlFetcher
                data-plasmic-name={"graphQlFetcher"}
                data-plasmic-override={overrides.graphQlFetcher}
                className={classNames("__wab_instance", sty.graphQlFetcher)}
                dataName={"fetchedData"}
                errorDisplay={
                  <DataCtxReader__>
                    {$ctx => "Error fetching data"}
                  </DataCtxReader__>
                }
                errorName={"fetchError"}
                headers={{
                  "Content-Type": "application/json",
                  Accept: "application/json",
                  apikey:
                    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmxkd3p1eW5yeXFibWFndWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODY5NTE4NjksImV4cCI6MjAwMjUyNzg2OX0.epN8z7ALKCjIWpz056OgbiL2Af1fg5W61yWXzGJALwA",
                  Authorization:
                    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmxkd3p1eW5yeXFibWFndWNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4Njk1MTg2OSwiZXhwIjoyMDAyNTI3ODY5fQ.Zg1jbFVl47RffMhBG1rM2XeAEJzUasurJxGPq78ACp0"
                }}
                loadingDisplay={
                  <DataCtxReader__>{$ctx => "Loading..."}</DataCtxReader__>
                }
                method={"POST"}
                noLayout={false}
                query={{
                  query:
                    "query gebruiker($usercheck: String!) {\n  usersCollection(filter: {email: {eq: $usercheck}}) {\n    edges {\n      node {\n        email\n        name\n        deftalentteam\n        defbookerteam\n      }\n    }\n  }\n}",
                  variables: {}
                }}
                url={"https://tsbldwzuynryqbmaguci.supabase.co/graphql/v1"}
                varOverrides={(() => {
                  try {
                    return { usercheck: $ctx.params.email };
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return {};
                    }
                    throw e;
                  }
                })()}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <ConditionGuard
                      data-plasmic-name={"conditionGuard"}
                      data-plasmic-override={overrides.conditionGuard}
                      className={classNames(
                        "__wab_instance",
                        sty.conditionGuard
                      )}
                      condition={(() => {
                        try {
                          return (
                            $ctx.fetchedData.data.usersCollection.edges[0].node
                              .defbookerteam === "" ||
                            $ctx.fetchedData.data.usersCollection.edges[0].node
                              .defbookerteam === null ||
                            $ctx.fetchedData.data.usersCollection.edges[0].node
                              .deftalentteam === "" ||
                            $ctx.fetchedData.data.usersCollection.edges[0].node
                              .deftalentteam === null
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return false;
                          }
                          throw e;
                        }
                      })()}
                      onNotSatisfied={async () => {
                        const $steps = {};

                        $steps["goToHomepage"] = true
                          ? (() => {
                              const actionArgs = { destination: `/` };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToHomepage"] != null &&
                          typeof $steps["goToHomepage"] === "object" &&
                          typeof $steps["goToHomepage"].then === "function"
                        ) {
                          $steps["goToHomepage"] = await $steps["goToHomepage"];
                        }
                      }}
                    >
                      <EmailVerificationHandler
                        data-plasmic-name={"emailVerificationHandler"}
                        data-plasmic-override={
                          overrides.emailVerificationHandler
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.emailVerificationHandler
                        )}
                        firstName={(() => {
                          try {
                            return JSON.parse(
                              $ctx.fetchedData.data.usersCollection.edges[0]
                                .node.name
                            ).first_name;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                      />

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sagZa
                          )}
                        >
                          <h2
                            data-plasmic-name={"h2"}
                            data-plasmic-override={overrides.h2}
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2
                            )}
                          >
                            {"Congratulations \ud83c\udf89"}
                          </h2>
                          <h3
                            data-plasmic-name={"h3"}
                            data-plasmic-override={overrides.h3}
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3
                            )}
                          >
                            {"Your email address is confirmed!"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tYe4
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {"Welcome to our community, "}
                              </React.Fragment>
                              {
                                <span
                                  data-plasmic-name={"span"}
                                  data-plasmic-override={overrides.span}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.span,
                                    projectcss.__wab_text,
                                    projectcss.plasmic_default__inline,
                                    sty.span
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return JSON.parse(
                                          $ctx.fetchedData.data.usersCollection
                                            .edges[0].node.name
                                        ).first_name;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "name";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </span>
                              }
                              <React.Fragment>
                                {
                                  "! We\u2019re excited to have you on board.\n\nTo help you get started, please let us know how you\u2019d like to use our platform. Are you here to showcase your talents, represent amazing performers, book the perfect talent for your next event, or support a booking team?\nSimply select the role that best describes you to continue.\n\nLet\u2019s get started\u2014choose your role below!"
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__gmDLa
                            )}
                          >
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__bw26R
                              )}
                              color={"clearDash"}
                              onClick={async event => {
                                const $steps = {};

                                $steps["goToPage"] = true
                                  ? (() => {
                                      const actionArgs = {
                                        destination: (() => {
                                          try {
                                            return "https://talent.offtoglow.com";
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                      };
                                      return (({ destination }) => {
                                        if (
                                          typeof destination === "string" &&
                                          destination.startsWith("#")
                                        ) {
                                          document
                                            .getElementById(
                                              destination.substr(1)
                                            )
                                            .scrollIntoView({
                                              behavior: "smooth"
                                            });
                                        } else {
                                          __nextRouter?.push(destination);
                                        }
                                      })?.apply(null, [actionArgs]);
                                    })()
                                  : undefined;
                                if (
                                  $steps["goToPage"] != null &&
                                  typeof $steps["goToPage"] === "object" &&
                                  typeof $steps["goToPage"].then === "function"
                                ) {
                                  $steps["goToPage"] = await $steps["goToPage"];
                                }
                              }}
                              selectLeft={true}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__p8Mnd
                                )}
                              >
                                <h4
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h4,
                                    projectcss.__wab_text,
                                    sty.h4__zc7U3
                                  )}
                                >
                                  {"Talent"}
                                </h4>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__u52Ni
                                  )}
                                >
                                  {"I am or representing a talent"}
                                </div>
                              </div>
                            </Button>
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__ssBh1
                              )}
                              color={"clearDash"}
                              onClick={async event => {
                                const $steps = {};

                                $steps["goToPage"] = true
                                  ? (() => {
                                      const actionArgs = {
                                        destination: (() => {
                                          try {
                                            return "https://booker.offtoglow.com";
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                      };
                                      return (({ destination }) => {
                                        if (
                                          typeof destination === "string" &&
                                          destination.startsWith("#")
                                        ) {
                                          document
                                            .getElementById(
                                              destination.substr(1)
                                            )
                                            .scrollIntoView({
                                              behavior: "smooth"
                                            });
                                        } else {
                                          __nextRouter?.push(destination);
                                        }
                                      })?.apply(null, [actionArgs]);
                                    })()
                                  : undefined;
                                if (
                                  $steps["goToPage"] != null &&
                                  typeof $steps["goToPage"] === "object" &&
                                  typeof $steps["goToPage"].then === "function"
                                ) {
                                  $steps["goToPage"] = await $steps["goToPage"];
                                }
                              }}
                              selectRight={true}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__btUw
                                )}
                              >
                                <h4
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h4,
                                    projectcss.__wab_text,
                                    sty.h4__gIzgl
                                  )}
                                >
                                  {"Booker"}
                                </h4>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__qozdn
                                  )}
                                >
                                  {"I am or representing a booker"}
                                </div>
                              </div>
                            </Button>
                          </Stack__>
                        </div>
                      ) : null}
                    </ConditionGuard>
                  )}
                </DataCtxReader__>
              </GraphqlFetcher>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "card",
    "graphQlFetcher",
    "conditionGuard",
    "emailVerificationHandler",
    "h2",
    "h3",
    "span"
  ],
  card: ["card"],
  graphQlFetcher: [
    "graphQlFetcher",
    "conditionGuard",
    "emailVerificationHandler",
    "h2",
    "h3",
    "span"
  ],
  conditionGuard: [
    "conditionGuard",
    "emailVerificationHandler",
    "h2",
    "h3",
    "span"
  ],
  emailVerificationHandler: ["emailVerificationHandler"],
  h2: ["h2"],
  h3: ["h3"],
  span: ["span"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  card: typeof Card;
  graphQlFetcher: typeof GraphqlFetcher;
  conditionGuard: typeof ConditionGuard;
  emailVerificationHandler: typeof EmailVerificationHandler;
  h2: "h2";
  h3: "h3";
  span: "span";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVerifcation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVerifcation__VariantsArgs;
    args?: PlasmicVerifcation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVerifcation__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVerifcation__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVerifcation__ArgProps,
          internalVariantPropNames: PlasmicVerifcation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVerifcation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVerifcation";
  } else {
    func.displayName = `PlasmicVerifcation.${nodeName}`;
  }
  return func;
}

export const PlasmicVerifcation = Object.assign(
  // Top-level PlasmicVerifcation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    card: makeNodeComponent("card"),
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    conditionGuard: makeNodeComponent("conditionGuard"),
    emailVerificationHandler: makeNodeComponent("emailVerificationHandler"),
    h2: makeNodeComponent("h2"),
    h3: makeNodeComponent("h3"),
    span: makeNodeComponent("span"),

    // Metadata about props expected for PlasmicVerifcation
    internalVariantProps: PlasmicVerifcation__VariantProps,
    internalArgProps: PlasmicVerifcation__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Email Verification | OfftoGlow",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicVerifcation;
/* prettier-ignore-end */
