/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: yqZlWocYh-A7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import Button from "../../Button"; // plasmic-import: bUjxyyacyjDo/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicAuthButton.module.css"; // plasmic-import: yqZlWocYh-A7/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: v7iefsRDFFri/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 4-aZVVDUZLRE/icon

createPlasmicElementProxy;

export type PlasmicAuthButton__VariantMembers = {
  buttonOnly: "buttonOnly";
  small: "small";
};
export type PlasmicAuthButton__VariantsArgs = {
  buttonOnly?: SingleBooleanChoiceArg<"buttonOnly">;
  small?: SingleBooleanChoiceArg<"small">;
};
type VariantPropType = keyof PlasmicAuthButton__VariantsArgs;
export const PlasmicAuthButton__VariantProps = new Array<VariantPropType>(
  "buttonOnly",
  "small"
);

export type PlasmicAuthButton__ArgsType = { onClick?: (event: any) => void };
type ArgPropType = keyof PlasmicAuthButton__ArgsType;
export const PlasmicAuthButton__ArgProps = new Array<ArgPropType>("onClick");

export type PlasmicAuthButton__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  loginBtn?: Flex__<typeof AntdButton>;
  button?: Flex__<typeof Button>;
};

export interface DefaultAuthButtonProps {
  onClick?: (event: any) => void;
  buttonOnly?: SingleBooleanChoiceArg<"buttonOnly">;
  small?: SingleBooleanChoiceArg<"small">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAuthButton__RenderFunc(props: {
  variants: PlasmicAuthButton__VariantsArgs;
  args: PlasmicAuthButton__ArgsType;
  overrides: PlasmicAuthButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "buttonOnly",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.buttonOnly
      },
      {
        path: "small",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.small
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        { [sty.rootsmall]: hasVariant($state, "small", "small") }
      )}
    >
      {(() => {
        try {
          return currentUser.isLoggedIn;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__nqdo, {
            [sty.freeBoxsmall__nqdOecu0V]: hasVariant($state, "small", "small")
          })}
        >
          {(
            hasVariant($state, "small", "small")
              ? false
              : hasVariant($state, "buttonOnly", "buttonOnly")
              ? false
              : false
          ) ? (
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img, {
                [sty.imgbuttonOnly]: hasVariant(
                  $state,
                  "buttonOnly",
                  "buttonOnly"
                ),
                [sty.imgsmall]: hasVariant($state, "small", "small")
              })}
              displayHeight={"32px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"32px"}
              loading={"lazy"}
            />
          ) : null}
          {(
            hasVariant($state, "small", "small")
              ? false
              : hasVariant($state, "buttonOnly", "buttonOnly")
              ? false
              : false
          ) ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bhi95,
                {
                  [sty.textbuttonOnly__bhi95Canv]: hasVariant(
                    $state,
                    "buttonOnly",
                    "buttonOnly"
                  ),
                  [sty.textsmall__bhi95Ecu0V]: hasVariant(
                    $state,
                    "small",
                    "small"
                  )
                }
              )}
            >
              {""}
            </div>
          ) : null}
        </Stack__>
      ) : null}
      {(() => {
        try {
          return !currentUser.isLoggedIn;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__uoaXv)}
        >
          <AntdButton
            data-plasmic-name={"loginBtn"}
            data-plasmic-override={overrides.loginBtn}
            className={classNames("__wab_instance", sty.loginBtn)}
            onClick={async () => {
              const $steps = {};

              $steps["goToAuth"] = true
                ? (() => {
                    const actionArgs = {};
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToAuth"] != null &&
                typeof $steps["goToAuth"] === "object" &&
                typeof $steps["goToAuth"].then === "function"
              ) {
                $steps["goToAuth"] = await $steps["goToAuth"];
              }
            }}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nrgDs
              )}
            >
              {"Login"}
            </div>
          </AntdButton>
        </Stack__>
      ) : null}
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
        color={"blue"}
        onClick={args.onClick}
        submitsForm={true}
      >
        {"Submit"}
      </Button>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "loginBtn", "button"],
  img: ["img"],
  loginBtn: ["loginBtn"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  loginBtn: typeof AntdButton;
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAuthButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAuthButton__VariantsArgs;
    args?: PlasmicAuthButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAuthButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAuthButton__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAuthButton__ArgProps,
          internalVariantPropNames: PlasmicAuthButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAuthButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAuthButton";
  } else {
    func.displayName = `PlasmicAuthButton.${nodeName}`;
  }
  return func;
}

export const PlasmicAuthButton = Object.assign(
  // Top-level PlasmicAuthButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    loginBtn: makeNodeComponent("loginBtn"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicAuthButton
    internalVariantProps: PlasmicAuthButton__VariantProps,
    internalArgProps: PlasmicAuthButton__ArgProps
  }
);

export default PlasmicAuthButton;
/* prettier-ignore-end */
