/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: S-xeQrVUnObh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Select from "../../Select"; // plasmic-import: f9wHHf_Tqns2/component
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query";
import { FormListWrapper } from "@plasmicpkgs/antd5/skinny/FormList";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import Button from "../../Button"; // plasmic-import: bUjxyyacyjDo/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicAuthForm.module.css"; // plasmic-import: S-xeQrVUnObh/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: v7iefsRDFFri/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 4-aZVVDUZLRE/icon

createPlasmicElementProxy;

export type PlasmicAuthForm__VariantMembers = {
  mode: "signIn" | "signUp" | "checkEmail" | "forgotPassword";
};
export type PlasmicAuthForm__VariantsArgs = {
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "forgotPassword">;
};
type VariantPropType = keyof PlasmicAuthForm__VariantsArgs;
export const PlasmicAuthForm__VariantProps = new Array<VariantPropType>("mode");

export type PlasmicAuthForm__ArgsType = {
  handleSubmit?: (mode: string, credentials: any) => void;
  currentMode?: string;
  onCurrentModeChange?: (val: string) => void;
  setResetEmail?: string;
  handlePasswordReset?: () => void;
};
type ArgPropType = keyof PlasmicAuthForm__ArgsType;
export const PlasmicAuthForm__ArgProps = new Array<ArgPropType>(
  "handleSubmit",
  "currentMode",
  "onCurrentModeChange",
  "setResetEmail",
  "handlePasswordReset"
);

export type PlasmicAuthForm__OverridesType = {
  root?: Flex__<"div">;
  httpRestApiFetcher?: Flex__<typeof DataFetcher>;
  form?: Flex__<typeof FormWrapper>;
  countrySelect?: Flex__<typeof AntdSelect>;
  credentialsForm?: Flex__<typeof FormWrapper>;
  firstNameInput?: Flex__<typeof AntdInput>;
  lastNameInput?: Flex__<typeof AntdInput>;
  cityInput?: Flex__<typeof AntdInput>;
  select?: Flex__<typeof Select>;
  emailInput?: Flex__<typeof AntdInput>;
  graphQlFetcher?: Flex__<typeof GraphqlFetcher>;
  ladvar?: Flex__<typeof FormWrapper>;
  emailcheck?: Flex__<typeof FormListWrapper>;
  passwordInput?: Flex__<typeof AntdPassword>;
  confirmPasswordInput?: Flex__<typeof AntdPassword>;
  ul?: Flex__<"ul">;
  forgotPasswordForm?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
};

export interface DefaultAuthFormProps {
  handleSubmit?: (mode: string, credentials: any) => void;
  currentMode?: string;
  onCurrentModeChange?: (val: string) => void;
  setResetEmail?: string;
  handlePasswordReset?: () => void;
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "forgotPassword">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAuthForm__RenderFunc(props: {
  variants: PlasmicAuthForm__VariantsArgs;
  args: PlasmicAuthForm__ArgsType;
  overrides: PlasmicAuthForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "credentialsForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "currentMode",
        type: "writable",
        variableType: "text",

        valueProp: "currentMode",
        onChangeProp: "onCurrentModeChange"
      },
      {
        path: "mode",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.currentMode;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.mode
      },
      {
        path: "credentialsForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "resetEmail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return undefined;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "forgotPasswordForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "forgotPasswordForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "forgotPasswordForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "forgotPasswordForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "emailInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "passwordInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      },
      {
        path: "confirmPasswordInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      },
      {
        path: "availEmail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "ladvar.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "ladvar",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "ladvar.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "ladvar",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "firstNameInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "lastNameInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "cityInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "countrySelect.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "country",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.form.value;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootmode_checkEmail]: hasVariant($state, "mode", "checkEmail"),
          [sty.rootmode_forgotPassword]: hasVariant(
            $state,
            "mode",
            "forgotPassword"
          ),
          [sty.rootmode_signIn]: hasVariant($state, "mode", "signIn"),
          [sty.rootmode_signUp]: hasVariant($state, "mode", "signUp")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__lK4YD, {
          [sty.freeBoxmode_checkEmail__lK4YDpTg7L]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_forgotPassword__lK4YDg8Geu]: hasVariant(
            $state,
            "mode",
            "forgotPassword"
          ),
          [sty.freeBoxmode_signIn__lK4YD0Uw3J]: hasVariant(
            $state,
            "mode",
            "signIn"
          ),
          [sty.freeBoxmode_signUp__lK4YDbzryM]: hasVariant(
            $state,
            "mode",
            "signUp"
          )
        })}
      >
        <DataFetcher
          data-plasmic-name={"httpRestApiFetcher"}
          data-plasmic-override={overrides.httpRestApiFetcher}
          className={classNames("__wab_instance", sty.httpRestApiFetcher)}
          dataName={"fetchedCountries"}
          errorDisplay={
            <DataCtxReader__>
              {$ctx => (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hoNx8
                  )}
                >
                  {"Error fetching data"}
                </div>
              )}
            </DataCtxReader__>
          }
          errorName={"fetchError"}
          headers={{
            "Content-Type": "application/json",
            Accept: "application/json",
            apikey:
              "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmxkd3p1eW5yeXFibWFndWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODY5NTE4NjksImV4cCI6MjAwMjUyNzg2OX0.epN8z7ALKCjIWpz056OgbiL2Af1fg5W61yWXzGJALwA",
            Authorization:
              "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmxkd3p1eW5yeXFibWFndWNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4Njk1MTg2OSwiZXhwIjoyMDAyNTI3ODY5fQ.Zg1jbFVl47RffMhBG1rM2XeAEJzUasurJxGPq78ACp0"
          }}
          loadingDisplay={
            <DataCtxReader__>
              {$ctx => (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fmd9W
                  )}
                >
                  {"Loading..."}
                </div>
              )}
            </DataCtxReader__>
          }
          method={"GET"}
          noLayout={false}
          queryKey={"country"}
          url={
            "https://tsbldwzuynryqbmaguci.supabase.co/rest/v1/typecountries?select=name&order=name.asc"
          }
        >
          <DataCtxReader__>
            {$ctx => (
              <React.Fragment>
                {(() => {
                  const child$Props = {
                    children: null,
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],
                    initialValues: (() => {
                      try {
                        return $ctx.fetchedCountries;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })(),
                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],
                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    />
                  );
                })()}
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__c4Mbt)}
                  >
                    <AntdSelect
                      data-plasmic-name={"countrySelect"}
                      data-plasmic-override={overrides.countrySelect}
                      bordered={false}
                      className={classNames(
                        "__wab_instance",
                        sty.countrySelect
                      )}
                      defaultOpen={false}
                      defaultStylesClassName={classNames(
                        projectcss.root_reset,
                        projectcss.plasmic_default_styles,
                        projectcss.plasmic_mixins,
                        projectcss.plasmic_tokens,
                        plasmic_antd_5_hostless_css.plasmic_tokens,
                        plasmic_plasmic_rich_components_css.plasmic_tokens
                      )}
                      mode={"single"}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "countrySelect",
                          "value"
                        ]).apply(null, eventArgs);
                      }}
                      options={(() => {
                        try {
                          return $ctx.fetchedCountries.map(item => ({
                            label: item.name,
                            value: item.name
                          }));
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return (() => {
                              const __composite = [
                                { type: "option", value: null, label: null },
                                { type: "option", value: null, label: null }
                              ];
                              __composite["0"]["value"] = "2";
                              __composite["0"]["label"] = "2";
                              __composite["1"]["value"] = "3";
                              __composite["1"]["label"] = "3";
                              return __composite;
                            })();
                          }
                          throw e;
                        }
                      })()}
                      placeholder={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f6YBt
                          )}
                        >
                          {"Select..."}
                        </div>
                      }
                      placeholderClassName={classNames({
                        [sty["pcls_miwbn8KTf9jN"]]: true
                      })}
                      popupScopeClassName={sty["countrySelect__popup"]}
                      showSearch={true}
                      useChildren={false}
                      value={generateStateValueProp($state, [
                        "countrySelect",
                        "value"
                      ])}
                    />
                  </div>
                ) : null}
              </React.Fragment>
            )}
          </DataCtxReader__>
        </DataFetcher>
        {(hasVariant($state, "mode", "forgotPassword") ? false : true)
          ? (() => {
              const child$Props = {
                className: classNames("__wab_instance", sty.credentialsForm, {
                  [sty.credentialsFormmode_checkEmail]: hasVariant(
                    $state,
                    "mode",
                    "checkEmail"
                  ),
                  [sty.credentialsFormmode_forgotPassword]: hasVariant(
                    $state,
                    "mode",
                    "forgotPassword"
                  ),
                  [sty.credentialsFormmode_signIn]: hasVariant(
                    $state,
                    "mode",
                    "signIn"
                  ),
                  [sty.credentialsFormmode_signUp]: hasVariant(
                    $state,
                    "mode",
                    "signUp"
                  )
                }),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["credentialsForm", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);

                  (async (changedValues, allValues) => {
                    const $steps = {};
                  }).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelCol: { span: 8, horizontalOnly: true },
                layout: "vertical",
                mode: "advanced",
                onFinish: async values => {
                  const $steps = {};

                  $steps["runHandleSubmit"] = true
                    ? (() => {
                        const actionArgs = {
                          eventRef: $props["handleSubmit"],
                          args: [
                            (() => {
                              try {
                                return $state.currentMode;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })(),
                            (() => {
                              try {
                                return $state.credentialsForm.value;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()
                          ]
                        };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runHandleSubmit"] != null &&
                    typeof $steps["runHandleSubmit"] === "object" &&
                    typeof $steps["runHandleSubmit"].then === "function"
                  ) {
                    $steps["runHandleSubmit"] = await $steps["runHandleSubmit"];
                  }
                },
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["credentialsForm", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["credentialsForm"] = ref;
                },
                submitSlot: null,
                wrapperCol: { span: 16, horizontalOnly: true }
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "credentialsForm.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "credentialsForm.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"credentialsForm"}
                  data-plasmic-override={overrides.credentialsForm}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__qihN
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__opxt
                        )}
                      >
                        {"First Name"}
                      </div>
                    }
                    name={"firstName"}
                    rules={[{ ruleType: "required", message: "Required" }]}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cqAuq)}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.firstNameInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["firstNameInput", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "First Name",
                          value: generateStateValueProp($state, [
                            "firstNameInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "firstNameInput.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"firstNameInput"}
                            data-plasmic-override={overrides.firstNameInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__d2Y8N
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bzroS
                        )}
                      >
                        {"Last Name"}
                      </div>
                    }
                    name={"lastName"}
                    rules={[{ ruleType: "required", message: "Required" }]}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__o1EcX)}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.lastNameInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["lastNameInput", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "Last Name",
                          value: generateStateValueProp($state, [
                            "lastNameInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "lastNameInput.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"lastNameInput"}
                            data-plasmic-override={overrides.lastNameInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField___0Slv9
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8UJiq
                        )}
                      >
                        {"City"}
                      </div>
                    }
                    name={"city"}
                    rules={[{ ruleType: "required", message: "Required" }]}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0R6WB
                      )}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.cityInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["cityInput", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "City",
                          value: generateStateValueProp($state, [
                            "cityInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "cityInput.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"cityInput"}
                            data-plasmic-override={overrides.cityInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField___61I63
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yRdxp
                        )}
                      >
                        {"City"}
                      </div>
                    }
                    name={"country"}
                    rules={[{ ruleType: "required", message: "Required" }]}
                  >
                    <Select
                      data-plasmic-name={"select"}
                      data-plasmic-override={overrides.select}
                      className={classNames("__wab_instance", sty.select)}
                      name={"country"}
                      onChange={async (...eventArgs: any) => {
                        ((...eventArgs) => {
                          generateStateOnChangeProp($state, [
                            "select",
                            "value"
                          ])(eventArgs[0]);
                        }).apply(null, eventArgs);

                        if (
                          eventArgs.length > 1 &&
                          eventArgs[1] &&
                          eventArgs[1]._plasmic_state_init_
                        ) {
                          return;
                        }
                      }}
                      options={(() => {
                        try {
                          return $state.country.map(item => ({
                            label: item.name,
                            value: item.name
                          }));
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [
                              { value: "option1", label: "Option 1" },
                              { value: "option2", label: "Option 2" }
                            ];
                          }
                          throw e;
                        }
                      })()}
                      value={generateStateValueProp($state, [
                        "select",
                        "value"
                      ])}
                    />
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__yjuFy
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ngI2I
                        )}
                      >
                        {"Email"}
                      </div>
                    }
                    name={"email"}
                    rules={[{ ruleType: "required", message: "Required" }]}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hjIgj)}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.emailInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["emailInput", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);

                            (async event => {
                              const $steps = {};

                              $steps["updateAvailEmail"] = true
                                ? (() => {
                                    const actionArgs = {
                                      variable: {
                                        objRoot: $state,
                                        variablePath: ["availEmail"]
                                      },
                                      operation: 0,
                                      value: $state.emailInput.value
                                    };
                                    return (({
                                      variable,
                                      value,
                                      startIndex,
                                      deleteCount
                                    }) => {
                                      if (!variable) {
                                        return;
                                      }
                                      const { objRoot, variablePath } =
                                        variable;

                                      $stateSet(objRoot, variablePath, value);
                                      return value;
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["updateAvailEmail"] != null &&
                                typeof $steps["updateAvailEmail"] ===
                                  "object" &&
                                typeof $steps["updateAvailEmail"].then ===
                                  "function"
                              ) {
                                $steps["updateAvailEmail"] = await $steps[
                                  "updateAvailEmail"
                                ];
                              }
                            }).apply(null, eventArgs);
                          },
                          placeholder: "Email",
                          value: generateStateValueProp($state, [
                            "emailInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "emailInput.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"emailInput"}
                            data-plasmic-override={overrides.emailInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                    {(() => {
                      try {
                        return (() => {
                          function getEmailError(email) {
                            if (!email || email.trim() === "") return false;
                            if (!email.includes("@")) {
                              return "\u26A0️ Missing @ symbol (e.g., name@domain.com)";
                            }
                            if ((email.match(/@/g) || []).length > 1) {
                              return "\u26A0️ Too many @ symbols";
                            }
                            const [localPart, domain] = email.split("@");
                            const lastDotIndex = domain.lastIndexOf(".");
                            if (lastDotIndex === -1) {
                              return "\u26A0️ Missing domain (e.g., name@domain.com)";
                            }
                            const tld = domain.slice(lastDotIndex + 1);
                            if (tld.length < 2) {
                              return "\u26A0️ Domain extension must be at least 2 characters (e.g., .com, .co)";
                            }
                            if (
                              domain.startsWith(".") ||
                              domain.endsWith(".")
                            ) {
                              return "\u26A0️ Invalid domain format (e.g., name@domain.com)";
                            }
                            return false;
                          }
                          const emailCheck = getEmailError(
                            $state.emailInput?.value
                          );
                          if (emailCheck === false) {
                            return false;
                          } else {
                            return emailCheck;
                          }
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kynSk
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return (() => {
                                function getEmailError(email) {
                                  if (!email || email.trim() === "")
                                    return false;
                                  if (!email.includes("@")) {
                                    return "\u26A0️ Missing @ symbol (e.g., name@domain.com)";
                                  }
                                  if ((email.match(/@/g) || []).length > 1) {
                                    return "\u26A0️ Too many @ symbols";
                                  }
                                  const [localPart, domain] = email.split("@");
                                  const lastDotIndex = domain.lastIndexOf(".");
                                  if (lastDotIndex === -1) {
                                    return "\u26A0️ Missing domain (e.g., name@domain.com)";
                                  }
                                  const tld = domain.slice(lastDotIndex + 1);
                                  if (tld.length < 2) {
                                    return "\u26A0️ Domain extension must be at least 2 characters (e.g., .com, .co)";
                                  }
                                  if (
                                    domain.startsWith(".") ||
                                    domain.endsWith(".")
                                  ) {
                                    return "\u26A0️ Invalid domain format (e.g., name@domain.com)";
                                  }
                                  return false;
                                }
                                const emailCheck = getEmailError(
                                  $state.emailInput?.value
                                );
                                if (emailCheck === false) {
                                  return false;
                                } else {
                                  return emailCheck;
                                }
                              })();
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Password is not the same\n";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    ) : null}
                    <GraphqlFetcher
                      data-plasmic-name={"graphQlFetcher"}
                      data-plasmic-override={overrides.graphQlFetcher}
                      className={classNames(
                        "__wab_instance",
                        sty.graphQlFetcher
                      )}
                      dataName={"fetchedEmail"}
                      errorDisplay={
                        <DataCtxReader__>
                          {$ctx => "Error fetching data"}
                        </DataCtxReader__>
                      }
                      errorName={"fetchError"}
                      headers={(() => {
                        try {
                          return {
                            "Content-Type": "application/json",
                            Accept: "application/json",
                            apikey:
                              "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmxkd3p1eW5yeXFibWFndWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODY5NTE4NjksImV4cCI6MjAwMjUyNzg2OX0.epN8z7ALKCjIWpz056OgbiL2Af1fg5W61yWXzGJALwA",
                            Authorization:
                              "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmxkd3p1eW5yeXFibWFndWNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4Njk1MTg2OSwiZXhwIjoyMDAyNTI3ODY5fQ.Zg1jbFVl47RffMhBG1rM2XeAEJzUasurJxGPq78ACp0"
                          };
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      loadingDisplay={
                        <DataCtxReader__>
                          {$ctx => (false ? "Loading..." : null)}
                        </DataCtxReader__>
                      }
                      method={"POST"}
                      noLayout={false}
                      query={{
                        query:
                          "query username($emailcheck: String!) {\n  usersCollection(filter: {email: {eq: $emailcheck}}) {\n    edges {\n      node {\n        email\n      }\n    }\n  }\n}"
                      }}
                      url={
                        "https://tsbldwzuynryqbmaguci.supabase.co/graphql/v1"
                      }
                      varOverrides={(() => {
                        try {
                          return { emailcheck: $state.availEmail };
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    >
                      <DataCtxReader__>
                        {$ctx => (
                          <React.Fragment>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__v1Naw
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (() => {
                                      return $state.ladvar.value.emailcheck
                                        ? "This email address is already registered."
                                        : false;
                                    })();
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "Password is not the same\n";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            {(() => {
                              const child$Props = {
                                className: classNames(
                                  "__wab_instance",
                                  sty.ladvar
                                ),
                                extendedOnValuesChange: async (
                                  ...eventArgs: any
                                ) => {
                                  generateStateOnChangePropForCodeComponents(
                                    $state,
                                    "value",
                                    ["ladvar", "value"],
                                    FormWrapper_Helpers
                                  ).apply(null, eventArgs);
                                },
                                formItems: [
                                  {
                                    label: "Name",
                                    name: "name",
                                    inputType: "Text"
                                  },
                                  {
                                    label: "Message",
                                    name: "message",
                                    inputType: "Text Area"
                                  }
                                ],
                                initialValues: (() => {
                                  try {
                                    return (() => {
                                      return $ctx.fetchedEmail?.data
                                        ?.usersCollection?.edges[0]?.node?.email
                                        ? true
                                        : false;
                                    })();
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                labelCol: { span: 8, horizontalOnly: true },
                                layout: "vertical",
                                mode: "advanced",
                                onIsSubmittingChange: async (
                                  ...eventArgs: any
                                ) => {
                                  generateStateOnChangePropForCodeComponents(
                                    $state,
                                    "isSubmitting",
                                    ["ladvar", "isSubmitting"],
                                    FormWrapper_Helpers
                                  ).apply(null, eventArgs);
                                },
                                ref: ref => {
                                  $refs["ladvar"] = ref;
                                },
                                submitSlot: null,
                                wrapperCol: { span: 16, horizontalOnly: true }
                              };
                              initializeCodeComponentStates(
                                $state,
                                [
                                  {
                                    name: "value",
                                    plasmicStateName: "ladvar.value"
                                  },
                                  {
                                    name: "isSubmitting",
                                    plasmicStateName: "ladvar.isSubmitting"
                                  }
                                ],
                                [],
                                FormWrapper_Helpers ?? {},
                                child$Props
                              );

                              return (
                                <FormWrapper
                                  data-plasmic-name={"ladvar"}
                                  data-plasmic-override={overrides.ladvar}
                                  {...child$Props}
                                >
                                  <FormListWrapper
                                    data-plasmic-name={"emailcheck"}
                                    data-plasmic-override={overrides.emailcheck}
                                    children={null}
                                    className={classNames(
                                      "__wab_instance",
                                      sty.emailcheck
                                    )}
                                    initialValue={(() => {
                                      try {
                                        return (() => {
                                          return $ctx.fetchedEmail?.data
                                            ?.usersCollection?.edges[0]?.node
                                            ?.email
                                            ? true
                                            : false;
                                        })();
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return {};
                                        }
                                        throw e;
                                      }
                                    })()}
                                    name={"emailcheck"}
                                    ref={ref => {
                                      $refs["emailcheck"] = ref;
                                    }}
                                  />
                                </FormWrapper>
                              );
                            })()}
                          </React.Fragment>
                        )}
                      </DataCtxReader__>
                    </GraphqlFetcher>
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField___1PVdn
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pMrXg
                        )}
                      >
                        {"Password"}
                      </div>
                    }
                    name={"password"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wtw4)}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.passwordInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["passwordInput", "value"],
                              AntdPassword_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder:
                            "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022",
                          value: generateStateValueProp($state, [
                            "passwordInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "passwordInput.value"
                            }
                          ],
                          [],
                          AntdPassword_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdPassword
                            data-plasmic-name={"passwordInput"}
                            data-plasmic-override={overrides.passwordInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                    {(() => {
                      try {
                        return (() => {
                          const isInvalid = !!(
                            $state.passwordInput.value &&
                            ($state.passwordInput.value.length < 8 ||
                              !/[A-Z]/.test($state.passwordInput.value) ||
                              !/[0-9]/.test($state.passwordInput.value))
                          );
                          return isInvalid;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3RHK
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return (() => {
                                function getPasswordError(password) {
                                  if (!password) return "Password is required.";
                                  if (password.length < 8) {
                                    return "Password must be at least 8 characters long.";
                                  }
                                  if (!/[A-Z]/.test(password)) {
                                    return "Password must contain at least one uppercase letter.";
                                  }
                                  if (!/[0-9]/.test(password)) {
                                    return "Password must contain at least one number.";
                                  }
                                  return null;
                                }
                                const errorMessage = getPasswordError(
                                  $state.passwordInput.value
                                );
                                if (errorMessage) {
                                  return errorMessage;
                                } else {
                                  return false;
                                }
                              })();
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Password is not the same\n";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    ) : null}
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__ufpNy
                    )}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r1Joz
                        )}
                      >
                        {"Confirm Password"}
                      </div>
                    }
                    name={"confirmpassword"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pY5Pi)}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.confirmPasswordInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["confirmPasswordInput", "value"],
                              AntdPassword_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder:
                            "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022",
                          value: generateStateValueProp($state, [
                            "confirmPasswordInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "confirmPasswordInput.value"
                            }
                          ],
                          [],
                          AntdPassword_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdPassword
                            data-plasmic-name={"confirmPasswordInput"}
                            data-plasmic-override={
                              overrides.confirmPasswordInput
                            }
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                    {(() => {
                      try {
                        return (() => {
                          return $state.confirmPasswordInput.value
                            ? $state.passwordInput.value !==
                                $state.confirmPasswordInput.value
                            : false;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nsWy
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return (() => {
                                if (
                                  $state.passwordInput.value !==
                                  $state.confirmPasswordInput.value
                                ) {
                                  return "Passwords do not match. Please ensure both entries are identical.";
                                }
                              })();
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Password is not the same\n";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    ) : null}
                  </FormItemWrapper>
                  {false ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8RCwZ
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rXAgO
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>
                            {
                              "Please enter a strong, new password below. Ensure it includes at least:\n\n"
                            }
                          </React.Fragment>
                          {
                            <ul
                              data-plasmic-name={"ul"}
                              data-plasmic-override={overrides.ul}
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__tCguR
                                )}
                              >
                                {"8 characters"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__oSz92
                                )}
                              >
                                {"1 uppercase letter"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__fmWOh
                                )}
                              >
                                {"1 number or special character"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>
                            {
                              "\nFor security, avoid using personal information or common words."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  ) : null}
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__f1AJh, {
                      [sty.buttonmode_signUp__f1AJhbzryM]: hasVariant(
                        $state,
                        "mode",
                        "signUp"
                      )
                    })}
                    disabled={(() => {
                      try {
                        return (() => {
                          const isEmailInvalid = email => {
                            if (!email || email.trim() === "") return false;
                            if (
                              !email.includes("@") ||
                              (email.match(/@/g) || []).length > 1
                            )
                              return true;
                            const [_, domain] = email.split("@");
                            const lastDotIndex = domain.lastIndexOf(".");
                            if (
                              lastDotIndex === -1 ||
                              domain.startsWith(".") ||
                              domain.endsWith(".")
                            )
                              return true;
                            const tld = domain.slice(lastDotIndex + 1);
                            return tld.length < 2;
                          };
                          const isPasswordInvalid =
                            !$state.passwordInput?.value ||
                            $state.passwordInput.value.length < 8 ||
                            !/[A-Z]/.test($state.passwordInput.value) ||
                            !/[0-9]/.test($state.passwordInput.value);
                          const doPasswordsDiffer =
                            $state.passwordInput?.value !==
                            $state.confirmPasswordInput?.value;
                          const isInvalid =
                            isEmailInvalid($state.emailInput?.value) ||
                            isPasswordInvalid ||
                            doPasswordsDiffer ||
                            $state.ladvar.value.emailcheck;
                          return isInvalid;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    onClick={async () => {
                      const $steps = {};
                    }}
                    shape={"default"}
                    size={"large"}
                    submitsForm={true}
                    type={"primary"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1YmOb,
                        {
                          [sty.textmode_signUp___1YmOBbzryM]: hasVariant(
                            $state,
                            "mode",
                            "signUp"
                          )
                        }
                      )}
                    >
                      {hasVariant($state, "mode", "signUp")
                        ? "Sign Up"
                        : "Create an account"}
                    </div>
                  </AntdButton>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___62Z5W
                    )}
                  >
                    {
                      "By registering, you agree to our Terms of Service and Privacy Policy."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___0G3Fe)}
                    color={"clearDash"}
                    onClick={async event => {
                      const $steps = {};

                      $steps["runCode"] = true
                        ? (() => {
                            const actionArgs = {
                              customFunction: async () => {
                                return history.back();
                              }
                            };
                            return (({ customFunction }) => {
                              return customFunction();
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["runCode"] != null &&
                        typeof $steps["runCode"] === "object" &&
                        typeof $steps["runCode"].then === "function"
                      ) {
                        $steps["runCode"] = await $steps["runCode"];
                      }
                    }}
                    size={"compact"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rmPhv
                      )}
                    >
                      {"Go Back"}
                    </div>
                  </Button>
                </FormWrapper>
              );
            })()
          : null}
        {(
          hasVariant($state, "mode", "forgotPassword")
            ? true
            : (() => {
                try {
                  return $state.mode === "forgotPassword";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })()
        )
          ? (() => {
              const child$Props = {
                className: classNames(
                  "__wab_instance",
                  sty.forgotPasswordForm,
                  {
                    [sty.forgotPasswordFormmode_checkEmail]: hasVariant(
                      $state,
                      "mode",
                      "checkEmail"
                    ),
                    [sty.forgotPasswordFormmode_forgotPassword]: hasVariant(
                      $state,
                      "mode",
                      "forgotPassword"
                    ),
                    [sty.forgotPasswordFormmode_signIn]: hasVariant(
                      $state,
                      "mode",
                      "signIn"
                    ),
                    [sty.forgotPasswordFormmode_signUp]: hasVariant(
                      $state,
                      "mode",
                      "signUp"
                    )
                  }
                ),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["forgotPasswordForm", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelCol: { span: 8, horizontalOnly: true },
                layout: "vertical",
                mode: "advanced",
                onFinish: async values => {
                  const $steps = {};

                  $steps["runHandleResetPassword"] = true
                    ? (() => {
                        const actionArgs = {
                          eventRef: $props["handlePasswordReset"]
                        };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runHandleResetPassword"] != null &&
                    typeof $steps["runHandleResetPassword"] === "object" &&
                    typeof $steps["runHandleResetPassword"].then === "function"
                  ) {
                    $steps["runHandleResetPassword"] = await $steps[
                      "runHandleResetPassword"
                    ];
                  }
                },
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["forgotPasswordForm", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["forgotPasswordForm"] = ref;
                },
                submitSlot: null,
                wrapperCol: { span: 16, horizontalOnly: true }
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "forgotPasswordForm.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "forgotPasswordForm.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"forgotPasswordForm"}
                  data-plasmic-override={overrides.forgotPasswordForm}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__suiHb,
                      {
                        [sty.formFieldmode_forgotPassword__suiHbg8Geu]:
                          hasVariant($state, "mode", "forgotPassword")
                      }
                    )}
                    label={"Email"}
                    name={
                      hasVariant($state, "mode", "forgotPassword")
                        ? "email"
                        : "resetEmail"
                    }
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.input),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["input", "value"],
                            AntdInput_Helpers
                          ).apply(null, eventArgs);
                        },
                        value: generateStateValueProp($state, [
                          "input",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "input.value"
                          }
                        ],
                        [],
                        AntdInput_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdInput
                          data-plasmic-name={"input"}
                          data-plasmic-override={overrides.input}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__eD2G, {
                      [sty.buttonmode_forgotPassword__eD2Gg8Geu]: hasVariant(
                        $state,
                        "mode",
                        "forgotPassword"
                      ),
                      [sty.buttonmode_signUp__eD2GbzryM]: hasVariant(
                        $state,
                        "mode",
                        "signUp"
                      )
                    })}
                    submitsForm={true}
                    type={"primary"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0ZAzb,
                        {
                          [sty.textmode_signUp___0ZAzBbzryM]: hasVariant(
                            $state,
                            "mode",
                            "signUp"
                          )
                        }
                      )}
                    >
                      {hasVariant($state, "mode", "signUp")
                        ? "Sign Up"
                        : "Sign In"}
                    </div>
                  </AntdButton>
                </FormWrapper>
              );
            })()
          : null}
        {false ? (
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__dLm3L, {
              [sty.freeBoxmode_checkEmail__dLm3LpTg7L]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              ),
              [sty.freeBoxmode_forgotPassword__dLm3Lg8Geu]: hasVariant(
                $state,
                "mode",
                "forgotPassword"
              ),
              [sty.freeBoxmode_signIn__dLm3L0Uw3J]: hasVariant(
                $state,
                "mode",
                "signIn"
              )
            })}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jcOcW,
                {
                  [sty.textmode_forgotPassword__jcOcWg8Geu]: hasVariant(
                    $state,
                    "mode",
                    "forgotPassword"
                  ),
                  [sty.textmode_signIn__jcOcW0Uw3J]: hasVariant(
                    $state,
                    "mode",
                    "signIn"
                  ),
                  [sty.textmode_signUp__jcOcWbzryM]: hasVariant(
                    $state,
                    "mode",
                    "signUp"
                  )
                }
              )}
              onClick={async event => {
                const $steps = {};

                $steps["updateCurrentMode"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["currentMode"]
                        },
                        operation: 0,
                        value:
                          $state.currentMode === "signIn"
                            ? "signUp"
                            : $state.currentMode === "signUp"
                            ? "signIn"
                            : "checkEmail"
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateCurrentMode"] != null &&
                  typeof $steps["updateCurrentMode"] === "object" &&
                  typeof $steps["updateCurrentMode"].then === "function"
                ) {
                  $steps["updateCurrentMode"] = await $steps[
                    "updateCurrentMode"
                  ];
                }
              }}
            >
              {hasVariant($state, "mode", "signUp")
                ? "Already have an account? Sign In Now"
                : "Don't have an account? Sign Up Now"}
            </div>
            {(() => {
              try {
                return $state.currentMode === "signIn";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__m6J7N,
                  {
                    [sty.textmode_forgotPassword__m6J7Ng8Geu]: hasVariant(
                      $state,
                      "mode",
                      "forgotPassword"
                    ),
                    [sty.textmode_signIn__m6J7N0Uw3J]: hasVariant(
                      $state,
                      "mode",
                      "signIn"
                    ),
                    [sty.textmode_signUp__m6J7NbzryM]: hasVariant(
                      $state,
                      "mode",
                      "signUp"
                    )
                  }
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToPasswordReset"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToPasswordReset"] != null &&
                    typeof $steps["goToPasswordReset"] === "object" &&
                    typeof $steps["goToPasswordReset"].then === "function"
                  ) {
                    $steps["goToPasswordReset"] = await $steps[
                      "goToPasswordReset"
                    ];
                  }
                }}
              >
                {hasVariant($state, "mode", "signUp")
                  ? "Already have an account? Sign In Now"
                  : "Forgot Password"}
              </div>
            ) : null}
          </Stack__>
        ) : null}
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ur4A0
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return JSON.stringify($state.credentialsForm.value);
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__rYk7C, {
          [sty.freeBoxmode_checkEmail__rYk7CpTg7L]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__rYk7C0Uw3J]: hasVariant(
            $state,
            "mode",
            "signIn"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__bbYhn,
            {
              [sty.textmode_checkEmail__bbYhnPTg7L]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              )
            }
          )}
        >
          {"Check your email"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "httpRestApiFetcher",
    "form",
    "countrySelect",
    "credentialsForm",
    "firstNameInput",
    "lastNameInput",
    "cityInput",
    "select",
    "emailInput",
    "graphQlFetcher",
    "ladvar",
    "emailcheck",
    "passwordInput",
    "confirmPasswordInput",
    "ul",
    "forgotPasswordForm",
    "input"
  ],
  httpRestApiFetcher: ["httpRestApiFetcher", "form", "countrySelect"],
  form: ["form"],
  countrySelect: ["countrySelect"],
  credentialsForm: [
    "credentialsForm",
    "firstNameInput",
    "lastNameInput",
    "cityInput",
    "select",
    "emailInput",
    "graphQlFetcher",
    "ladvar",
    "emailcheck",
    "passwordInput",
    "confirmPasswordInput",
    "ul"
  ],
  firstNameInput: ["firstNameInput"],
  lastNameInput: ["lastNameInput"],
  cityInput: ["cityInput"],
  select: ["select"],
  emailInput: ["emailInput"],
  graphQlFetcher: ["graphQlFetcher", "ladvar", "emailcheck"],
  ladvar: ["ladvar", "emailcheck"],
  emailcheck: ["emailcheck"],
  passwordInput: ["passwordInput"],
  confirmPasswordInput: ["confirmPasswordInput"],
  ul: ["ul"],
  forgotPasswordForm: ["forgotPasswordForm", "input"],
  input: ["input"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  httpRestApiFetcher: typeof DataFetcher;
  form: typeof FormWrapper;
  countrySelect: typeof AntdSelect;
  credentialsForm: typeof FormWrapper;
  firstNameInput: typeof AntdInput;
  lastNameInput: typeof AntdInput;
  cityInput: typeof AntdInput;
  select: typeof Select;
  emailInput: typeof AntdInput;
  graphQlFetcher: typeof GraphqlFetcher;
  ladvar: typeof FormWrapper;
  emailcheck: typeof FormListWrapper;
  passwordInput: typeof AntdPassword;
  confirmPasswordInput: typeof AntdPassword;
  ul: "ul";
  forgotPasswordForm: typeof FormWrapper;
  input: typeof AntdInput;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAuthForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAuthForm__VariantsArgs;
    args?: PlasmicAuthForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAuthForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAuthForm__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAuthForm__ArgProps,
          internalVariantPropNames: PlasmicAuthForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAuthForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAuthForm";
  } else {
    func.displayName = `PlasmicAuthForm.${nodeName}`;
  }
  return func;
}

export const PlasmicAuthForm = Object.assign(
  // Top-level PlasmicAuthForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    form: makeNodeComponent("form"),
    countrySelect: makeNodeComponent("countrySelect"),
    credentialsForm: makeNodeComponent("credentialsForm"),
    firstNameInput: makeNodeComponent("firstNameInput"),
    lastNameInput: makeNodeComponent("lastNameInput"),
    cityInput: makeNodeComponent("cityInput"),
    select: makeNodeComponent("select"),
    emailInput: makeNodeComponent("emailInput"),
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    ladvar: makeNodeComponent("ladvar"),
    emailcheck: makeNodeComponent("emailcheck"),
    passwordInput: makeNodeComponent("passwordInput"),
    confirmPasswordInput: makeNodeComponent("confirmPasswordInput"),
    ul: makeNodeComponent("ul"),
    forgotPasswordForm: makeNodeComponent("forgotPasswordForm"),
    input: makeNodeComponent("input"),

    // Metadata about props expected for PlasmicAuthForm
    internalVariantProps: PlasmicAuthForm__VariantProps,
    internalArgProps: PlasmicAuthForm__ArgProps
  }
);

export default PlasmicAuthForm;
/* prettier-ignore-end */
