/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: OXtcbqP4qn4B

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "../about_offtoglow_com/plasmic"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectModule
import { _useStyleTokens } from "../about_offtoglow_com/PlasmicStyleTokensProvider"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicPasswordResetForm.module.css"; // plasmic-import: OXtcbqP4qn4B/css

createPlasmicElementProxy;

export type PlasmicPasswordResetForm__VariantMembers = {
  mode: "signIn" | "signUp" | "checkEmail" | "resetEmail";
};
export type PlasmicPasswordResetForm__VariantsArgs = {
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "resetEmail">;
};
type VariantPropType = keyof PlasmicPasswordResetForm__VariantsArgs;
export const PlasmicPasswordResetForm__VariantProps =
  new Array<VariantPropType>("mode");

export type PlasmicPasswordResetForm__ArgsType = {
  handleSubmit?: (mode: string, credentials: any) => void;
  setResetEmail?: string;
  handleResetPassword?: () => void;
};
type ArgPropType = keyof PlasmicPasswordResetForm__ArgsType;
export const PlasmicPasswordResetForm__ArgProps = new Array<ArgPropType>(
  "handleSubmit",
  "setResetEmail",
  "handleResetPassword"
);

export type PlasmicPasswordResetForm__OverridesType = {
  root?: Flex__<"div">;
  updatePasswordForm?: Flex__<typeof FormWrapper>;
  formField?: Flex__<typeof FormItemWrapper>;
  h3?: Flex__<"h3">;
  input?: Flex__<typeof AntdInput>;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultPasswordResetFormProps {
  handleSubmit?: (mode: string, credentials: any) => void;
  setResetEmail?: string;
  handleResetPassword?: () => void;
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "resetEmail">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPasswordResetForm__RenderFunc(props: {
  variants: PlasmicPasswordResetForm__VariantsArgs;
  args: PlasmicPasswordResetForm__ArgsType;
  overrides: PlasmicPasswordResetForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "currentMode",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "signIn"
      },
      {
        path: "mode",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.currentMode;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.mode
      },
      {
        path: "resetEmail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "updatePasswordForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "updatePasswordForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "updatePasswordForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "updatePasswordForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root,
        {
          [sty.rootmode_checkEmail]: hasVariant($state, "mode", "checkEmail"),
          [sty.rootmode_resetEmail]: hasVariant($state, "mode", "resetEmail"),
          [sty.rootmode_signIn]: hasVariant($state, "mode", "signIn"),
          [sty.rootmode_signUp]: hasVariant($state, "mode", "signUp")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__xeQxW, {
          [sty.freeBoxmode_checkEmail__xeQxWj5Cf]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__xeQxWi6Ifa]: hasVariant(
            $state,
            "mode",
            "signIn"
          ),
          [sty.freeBoxmode_signUp__xeQxWQdpnb]: hasVariant(
            $state,
            "mode",
            "signUp"
          )
        })}
      >
        {(() => {
          const child$Props = {
            className: classNames("__wab_instance", sty.updatePasswordForm, {
              [sty.updatePasswordFormmode_checkEmail]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              ),
              [sty.updatePasswordFormmode_resetEmail]: hasVariant(
                $state,
                "mode",
                "resetEmail"
              ),
              [sty.updatePasswordFormmode_signIn]: hasVariant(
                $state,
                "mode",
                "signIn"
              ),
              [sty.updatePasswordFormmode_signUp]: hasVariant(
                $state,
                "mode",
                "signUp"
              )
            }),
            extendedOnValuesChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "value",
                ["updatePasswordForm", "value"],
                FormWrapper_Helpers
              ).apply(null, eventArgs);
            },
            formItems: [
              { label: "Name", name: "name", inputType: "Text" },
              { label: "Message", name: "message", inputType: "Text Area" }
            ],
            labelCol: { span: 8, horizontalOnly: true },
            layout: "vertical",
            mode: "advanced",
            onFinish: async values => {
              const $steps = {};

              $steps["runHandleSubmit"] = true
                ? (() => {
                    const actionArgs = {
                      eventRef: $props["handleSubmit"],
                      args: [
                        (() => {
                          try {
                            return $state.currentMode;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })(),
                        (() => {
                          try {
                            return $state.updatePasswordForm.value.email;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      ]
                    };
                    return (({ eventRef, args }) => {
                      return eventRef?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runHandleSubmit"] != null &&
                typeof $steps["runHandleSubmit"] === "object" &&
                typeof $steps["runHandleSubmit"].then === "function"
              ) {
                $steps["runHandleSubmit"] = await $steps["runHandleSubmit"];
              }
            },
            onIsSubmittingChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "isSubmitting",
                ["updatePasswordForm", "isSubmitting"],
                FormWrapper_Helpers
              ).apply(null, eventArgs);
            },
            ref: ref => {
              $refs["updatePasswordForm"] = ref;
            },
            submitSlot: null,
            wrapperCol: { span: 16, horizontalOnly: true }
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "value",
                plasmicStateName: "updatePasswordForm.value"
              },
              {
                name: "isSubmitting",
                plasmicStateName: "updatePasswordForm.isSubmitting"
              }
            ],
            [],
            FormWrapper_Helpers ?? {},
            child$Props
          );

          return (
            <FormWrapper
              data-plasmic-name={"updatePasswordForm"}
              data-plasmic-override={overrides.updatePasswordForm}
              {...child$Props}
            >
              <FormItemWrapper
                data-plasmic-name={"formField"}
                data-plasmic-override={overrides.formField}
                className={classNames("__wab_instance", sty.formField)}
                initialValue={$state.input.value}
                label={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qi5WN)}
                  >
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {"Please Enter Your Email"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tt50M
                      )}
                    >
                      {
                        "Enter your email address below. You will receive a password reset link within a few minutes. Click the link in the email to create a new password."
                      }
                    </div>
                  </div>
                }
                name={"email"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__yPc1S)}>
                  {(() => {
                    const child$Props = {
                      bordered: false,
                      className: classNames("__wab_instance", sty.input),
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["input", "value"],
                          AntdInput_Helpers
                        ).apply(null, eventArgs);
                      },
                      placeholder: "Enter Your Email",
                      value: generateStateValueProp($state, ["input", "value"])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "input.value"
                        }
                      ],
                      [],
                      AntdInput_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdInput
                        data-plasmic-name={"input"}
                        data-plasmic-override={overrides.input}
                        {...child$Props}
                      />
                    );
                  })()}
                </div>
              </FormItemWrapper>
              <AntdButton
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames("__wab_instance", sty.button, {
                  [sty.buttonmode_signUp]: hasVariant($state, "mode", "signUp")
                })}
                size={"large"}
                submitsForm={true}
                type={"primary"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cL5Op,
                    {
                      [sty.textmode_signUp__cL5OpQdpnb]: hasVariant(
                        $state,
                        "mode",
                        "signUp"
                      )
                    }
                  )}
                >
                  {hasVariant($state, "mode", "signUp")
                    ? "Sign Up"
                    : "Send Reset Link"}
                </div>
              </AntdButton>
            </FormWrapper>
          );
        })()}
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__gIX, {
          [sty.freeBoxmode_checkEmail__gIXJ5Cf]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__gIXI6Ifa]: hasVariant(
            $state,
            "mode",
            "signIn"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__c7QK,
            {
              [sty.textmode_checkEmail__c7QKJ5Cf]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              )
            }
          )}
        >
          {"Check your email"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "updatePasswordForm", "formField", "h3", "input", "button"],
  updatePasswordForm: [
    "updatePasswordForm",
    "formField",
    "h3",
    "input",
    "button"
  ],
  formField: ["formField", "h3", "input"],
  h3: ["h3"],
  input: ["input"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  updatePasswordForm: typeof FormWrapper;
  formField: typeof FormItemWrapper;
  h3: "h3";
  input: typeof AntdInput;
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPasswordResetForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPasswordResetForm__VariantsArgs;
    args?: PlasmicPasswordResetForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPasswordResetForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPasswordResetForm__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPasswordResetForm__ArgProps,
          internalVariantPropNames: PlasmicPasswordResetForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPasswordResetForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPasswordResetForm";
  } else {
    func.displayName = `PlasmicPasswordResetForm.${nodeName}`;
  }
  return func;
}

export const PlasmicPasswordResetForm = Object.assign(
  // Top-level PlasmicPasswordResetForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    updatePasswordForm: makeNodeComponent("updatePasswordForm"),
    formField: makeNodeComponent("formField"),
    h3: makeNodeComponent("h3"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicPasswordResetForm
    internalVariantProps: PlasmicPasswordResetForm__VariantProps,
    internalArgProps: PlasmicPasswordResetForm__ArgProps
  }
);

export default PlasmicPasswordResetForm;
/* prettier-ignore-end */
