/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: BiWy8ZTZvLL1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Card from "../../Card"; // plasmic-import: twFopKdKGk6j/component
import UpdatePasswordForm from "../../UpdatePasswordForm"; // plasmic-import: E2Q3fYpTWWgF/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicPw.module.css"; // plasmic-import: BiWy8ZTZvLL1/css

createPlasmicElementProxy;

export type PlasmicPw__VariantMembers = {};
export type PlasmicPw__VariantsArgs = {};
type VariantPropType = keyof PlasmicPw__VariantsArgs;
export const PlasmicPw__VariantProps = new Array<VariantPropType>();

export type PlasmicPw__ArgsType = {};
type ArgPropType = keyof PlasmicPw__ArgsType;
export const PlasmicPw__ArgProps = new Array<ArgPropType>();

export type PlasmicPw__OverridesType = {
  root?: Flex__<"div">;
  card?: Flex__<typeof Card>;
  text?: Flex__<"div">;
  updatePasswordForm?: Flex__<typeof UpdatePasswordForm>;
};

export interface DefaultPwProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPw__RenderFunc(props: {
  variants: PlasmicPw__VariantsArgs;
  args: PlasmicPw__ArgsType;
  overrides: PlasmicPw__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPw.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPw.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPw.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.root
        )}
      >
        <div className={classNames(projectcss.all, sty.freeBox__xXbbE)}>
          <div className={classNames(projectcss.all, sty.freeBox__nOrvm)}>
            <Card
              data-plasmic-name={"card"}
              data-plasmic-override={overrides.card}
              className={classNames("__wab_instance", sty.card)}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"\u00a9 Rob Csaszar"}
              </div>
            </Card>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__sRbxk)}>
            <UpdatePasswordForm
              data-plasmic-name={"updatePasswordForm"}
              data-plasmic-override={overrides.updatePasswordForm}
              className={classNames("__wab_instance", sty.updatePasswordForm)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "card", "text", "updatePasswordForm"],
  card: ["card", "text"],
  text: ["text"],
  updatePasswordForm: ["updatePasswordForm"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  card: typeof Card;
  text: "div";
  updatePasswordForm: typeof UpdatePasswordForm;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPw__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPw__VariantsArgs;
    args?: PlasmicPw__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPw__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPw__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPw__ArgProps,
          internalVariantPropNames: PlasmicPw__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPw__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPw";
  } else {
    func.displayName = `PlasmicPw.${nodeName}`;
  }
  return func;
}

export const PlasmicPw = Object.assign(
  // Top-level PlasmicPw renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    card: makeNodeComponent("card"),
    text: makeNodeComponent("text"),
    updatePasswordForm: makeNodeComponent("updatePasswordForm"),

    // Metadata about props expected for PlasmicPw
    internalVariantProps: PlasmicPw__VariantProps,
    internalArgProps: PlasmicPw__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Create a New Password || OfftoGlow",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPw;
/* prettier-ignore-end */
