/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: E2Q3fYpTWWgF

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicUpdatePasswordForm.module.css"; // plasmic-import: E2Q3fYpTWWgF/css

createPlasmicElementProxy;

export type PlasmicUpdatePasswordForm__VariantMembers = {
  mode: "signIn" | "signUp" | "checkEmail" | "resetEmail";
};
export type PlasmicUpdatePasswordForm__VariantsArgs = {
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "resetEmail">;
};
type VariantPropType = keyof PlasmicUpdatePasswordForm__VariantsArgs;
export const PlasmicUpdatePasswordForm__VariantProps =
  new Array<VariantPropType>("mode");

export type PlasmicUpdatePasswordForm__ArgsType = {
  handleSubmit?: (mode: string, credentials: any) => void;
  setResetEmail?: string;
  handleResetPassword?: () => void;
};
type ArgPropType = keyof PlasmicUpdatePasswordForm__ArgsType;
export const PlasmicUpdatePasswordForm__ArgProps = new Array<ArgPropType>(
  "handleSubmit",
  "setResetEmail",
  "handleResetPassword"
);

export type PlasmicUpdatePasswordForm__OverridesType = {
  root?: Flex__<"div">;
  updatePasswordForm?: Flex__<typeof FormWrapper>;
  formField?: Flex__<typeof FormItemWrapper>;
  h3?: Flex__<"h3">;
  ul?: Flex__<"ul">;
  passwordInput?: Flex__<typeof AntdPassword>;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultUpdatePasswordFormProps {
  handleSubmit?: (mode: string, credentials: any) => void;
  setResetEmail?: string;
  handleResetPassword?: () => void;
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "resetEmail">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUpdatePasswordForm__RenderFunc(props: {
  variants: PlasmicUpdatePasswordForm__VariantsArgs;
  args: PlasmicUpdatePasswordForm__ArgsType;
  overrides: PlasmicUpdatePasswordForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "currentMode",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "signIn"
      },
      {
        path: "mode",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.currentMode;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.mode
      },
      {
        path: "resetEmail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "updatePasswordForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "updatePasswordForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "updatePasswordForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "updatePasswordForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "passwordInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootmode_checkEmail]: hasVariant($state, "mode", "checkEmail"),
          [sty.rootmode_resetEmail]: hasVariant($state, "mode", "resetEmail"),
          [sty.rootmode_signIn]: hasVariant($state, "mode", "signIn"),
          [sty.rootmode_signUp]: hasVariant($state, "mode", "signUp")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__ktHCy, {
          [sty.freeBoxmode_checkEmail__ktHCymWajw]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__ktHCyYlSbW]: hasVariant(
            $state,
            "mode",
            "signIn"
          ),
          [sty.freeBoxmode_signUp__ktHCy87BXa]: hasVariant(
            $state,
            "mode",
            "signUp"
          )
        })}
      >
        {(() => {
          const child$Props = {
            className: classNames("__wab_instance", sty.updatePasswordForm, {
              [sty.updatePasswordFormmode_checkEmail]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              ),
              [sty.updatePasswordFormmode_resetEmail]: hasVariant(
                $state,
                "mode",
                "resetEmail"
              ),
              [sty.updatePasswordFormmode_signIn]: hasVariant(
                $state,
                "mode",
                "signIn"
              ),
              [sty.updatePasswordFormmode_signUp]: hasVariant(
                $state,
                "mode",
                "signUp"
              )
            }),
            extendedOnValuesChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "value",
                ["updatePasswordForm", "value"],
                FormWrapper_Helpers
              ).apply(null, eventArgs);
            },
            formItems: [
              { label: "Name", name: "name", inputType: "Text" },
              { label: "Message", name: "message", inputType: "Text Area" }
            ],
            labelCol: { span: 8, horizontalOnly: true },
            layout: "vertical",
            mode: "advanced",
            onFinish: async values => {
              const $steps = {};

              $steps["runHandleResetPassword"] = true
                ? (() => {
                    const actionArgs = {
                      eventRef: $props["handleResetPassword"]
                    };
                    return (({ eventRef, args }) => {
                      return eventRef?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runHandleResetPassword"] != null &&
                typeof $steps["runHandleResetPassword"] === "object" &&
                typeof $steps["runHandleResetPassword"].then === "function"
              ) {
                $steps["runHandleResetPassword"] = await $steps[
                  "runHandleResetPassword"
                ];
              }
            },
            onIsSubmittingChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "isSubmitting",
                ["updatePasswordForm", "isSubmitting"],
                FormWrapper_Helpers
              ).apply(null, eventArgs);
            },
            ref: ref => {
              $refs["updatePasswordForm"] = ref;
            },
            submitSlot: null,
            wrapperCol: { span: 16, horizontalOnly: true }
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "value",
                plasmicStateName: "updatePasswordForm.value"
              },
              {
                name: "isSubmitting",
                plasmicStateName: "updatePasswordForm.isSubmitting"
              }
            ],
            [],
            FormWrapper_Helpers ?? {},
            child$Props
          );

          return (
            <FormWrapper
              data-plasmic-name={"updatePasswordForm"}
              data-plasmic-override={overrides.updatePasswordForm}
              {...child$Props}
            >
              <FormItemWrapper
                data-plasmic-name={"formField"}
                data-plasmic-override={overrides.formField}
                className={classNames("__wab_instance", sty.formField)}
                label={
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___8Sr7E)}
                  >
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {"Create a New Password"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pWw7C
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__teUUq
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "Please enter a strong, new password below. Ensure it includes at least:\n\n\n"
                                }
                              </React.Fragment>
                              {
                                <ul
                                  data-plasmic-name={"ul"}
                                  data-plasmic-override={overrides.ul}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__uKr9O
                                    )}
                                  >
                                    {"8 characters\n"}
                                  </li>
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li___33Qr
                                    )}
                                  >
                                    {"1 uppercase letter"}
                                  </li>
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li___8BBWe
                                    )}
                                  >
                                    {"1 number or special character"}
                                  </li>
                                </ul>
                              }
                              <React.Fragment>
                                {
                                  "\nFor security, avoid using personal information or common words."
                                }
                              </React.Fragment>
                            </React.Fragment>
                          </li>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </Stack__>
                }
                name={"setNewPassword"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__eXbj5)}>
                  {(() => {
                    const child$Props = {
                      bordered: false,
                      className: classNames(
                        "__wab_instance",
                        sty.passwordInput
                      ),
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["passwordInput", "value"],
                          AntdPassword_Helpers
                        ).apply(null, eventArgs);
                      },
                      placeholder:
                        "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022",
                      value: generateStateValueProp($state, [
                        "passwordInput",
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "passwordInput.value"
                        }
                      ],
                      [],
                      AntdPassword_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdPassword
                        data-plasmic-name={"passwordInput"}
                        data-plasmic-override={overrides.passwordInput}
                        {...child$Props}
                      />
                    );
                  })()}
                </div>
              </FormItemWrapper>
              <AntdButton
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames("__wab_instance", sty.button, {
                  [sty.buttonmode_signUp]: hasVariant($state, "mode", "signUp")
                })}
                size={"large"}
                submitsForm={true}
                type={"primary"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h8Pre,
                    {
                      [sty.textmode_signUp__h8Pre87BXa]: hasVariant(
                        $state,
                        "mode",
                        "signUp"
                      )
                    }
                  )}
                >
                  {hasVariant($state, "mode", "signUp")
                    ? "Sign Up"
                    : "Change Password"}
                </div>
              </AntdButton>
            </FormWrapper>
          );
        })()}
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox___6PvaR, {
          [sty.freeBoxmode_checkEmail___6PvaRmWajw]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn___6PvaRYlSbW]: hasVariant(
            $state,
            "mode",
            "signIn"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__gw7Yj,
            {
              [sty.textmode_checkEmail__gw7YJmWajw]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              )
            }
          )}
        >
          {"Check your email"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "updatePasswordForm",
    "formField",
    "h3",
    "ul",
    "passwordInput",
    "button"
  ],
  updatePasswordForm: [
    "updatePasswordForm",
    "formField",
    "h3",
    "ul",
    "passwordInput",
    "button"
  ],
  formField: ["formField", "h3", "ul", "passwordInput"],
  h3: ["h3"],
  ul: ["ul"],
  passwordInput: ["passwordInput"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  updatePasswordForm: typeof FormWrapper;
  formField: typeof FormItemWrapper;
  h3: "h3";
  ul: "ul";
  passwordInput: typeof AntdPassword;
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUpdatePasswordForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUpdatePasswordForm__VariantsArgs;
    args?: PlasmicUpdatePasswordForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUpdatePasswordForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicUpdatePasswordForm__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUpdatePasswordForm__ArgProps,
          internalVariantPropNames: PlasmicUpdatePasswordForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUpdatePasswordForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUpdatePasswordForm";
  } else {
    func.displayName = `PlasmicUpdatePasswordForm.${nodeName}`;
  }
  return func;
}

export const PlasmicUpdatePasswordForm = Object.assign(
  // Top-level PlasmicUpdatePasswordForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    updatePasswordForm: makeNodeComponent("updatePasswordForm"),
    formField: makeNodeComponent("formField"),
    h3: makeNodeComponent("h3"),
    ul: makeNodeComponent("ul"),
    passwordInput: makeNodeComponent("passwordInput"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicUpdatePasswordForm
    internalVariantProps: PlasmicUpdatePasswordForm__VariantProps,
    internalArgProps: PlasmicUpdatePasswordForm__ArgProps
  }
);

export default PlasmicUpdatePasswordForm;
/* prettier-ignore-end */
