/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: zLEruNHWfm1A

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicPwForm.module.css"; // plasmic-import: zLEruNHWfm1A/css

createPlasmicElementProxy;

export type PlasmicPwForm__VariantMembers = {};
export type PlasmicPwForm__VariantsArgs = {};
type VariantPropType = keyof PlasmicPwForm__VariantsArgs;
export const PlasmicPwForm__VariantProps = new Array<VariantPropType>();

export type PlasmicPwForm__ArgsType = {
  handleSubmit?: (mode: string, credentials: any) => void;
  fetchCurrentUser?: string;
};
type ArgPropType = keyof PlasmicPwForm__ArgsType;
export const PlasmicPwForm__ArgProps = new Array<ArgPropType>(
  "handleSubmit",
  "fetchCurrentUser"
);

export type PlasmicPwForm__OverridesType = {
  root?: Flex__<"div">;
  credentialsForm?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultPwFormProps {
  handleSubmit?: (mode: string, credentials: any) => void;
  fetchCurrentUser?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPwForm__RenderFunc(props: {
  variants: PlasmicPwForm__VariantsArgs;
  args: PlasmicPwForm__ArgsType;
  overrides: PlasmicPwForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "credentialsForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "currentMode",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "signIn"
      },
      {
        path: "credentialsForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return currentUser.email;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__dr9Le)}>
        {(() => {
          const child$Props = {
            className: classNames("__wab_instance", sty.credentialsForm),
            extendedOnValuesChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "value",
                ["credentialsForm", "value"],
                FormWrapper_Helpers
              ).apply(null, eventArgs);
            },
            formItems: undefined,
            labelCol: { span: 8, horizontalOnly: true },
            layout: "vertical",
            mode: undefined,
            onFinish: async values => {
              const $steps = {};

              $steps["runActionOnCredentialsForm"] = true
                ? (() => {
                    const actionArgs = {
                      tplRef: "credentialsForm",
                      action: "setFieldValue",
                      args: [["$props", "fetchCurrentUser"], $state.variable]
                    };
                    return (({ tplRef, action, args }) => {
                      return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runActionOnCredentialsForm"] != null &&
                typeof $steps["runActionOnCredentialsForm"] === "object" &&
                typeof $steps["runActionOnCredentialsForm"].then === "function"
              ) {
                $steps["runActionOnCredentialsForm"] = await $steps[
                  "runActionOnCredentialsForm"
                ];
              }

              $steps["runHandleSubmit"] = true
                ? (() => {
                    const actionArgs = {
                      eventRef: $props["handleSubmit"],
                      args: [
                        (() => {
                          try {
                            return $state.currentMode;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })(),
                        (() => {
                          try {
                            return $state.credentialsForm.value;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      ]
                    };
                    return (({ eventRef, args }) => {
                      return eventRef?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runHandleSubmit"] != null &&
                typeof $steps["runHandleSubmit"] === "object" &&
                typeof $steps["runHandleSubmit"].then === "function"
              ) {
                $steps["runHandleSubmit"] = await $steps["runHandleSubmit"];
              }
            },
            onIsSubmittingChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "isSubmitting",
                ["credentialsForm", "isSubmitting"],
                FormWrapper_Helpers
              ).apply(null, eventArgs);
            },
            ref: ref => {
              $refs["credentialsForm"] = ref;
            },
            wrapperCol: { span: 16, horizontalOnly: true }
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "value",
                plasmicStateName: "credentialsForm.value"
              },
              {
                name: "isSubmitting",
                plasmicStateName: "credentialsForm.isSubmitting"
              }
            ],
            [],
            FormWrapper_Helpers ?? {},
            child$Props
          );

          return (
            <FormWrapper
              data-plasmic-name={"credentialsForm"}
              data-plasmic-override={overrides.credentialsForm}
              {...child$Props}
            >
              <FormItemWrapper
                className={classNames("__wab_instance", sty.formField__qmTsA)}
                label={"Email"}
                name={"email"}
              >
                <AntdInput
                  className={classNames("__wab_instance", sty.input)}
                />
              </FormItemWrapper>
              <FormItemWrapper
                className={classNames("__wab_instance", sty.formField__zkKqk)}
                label={"Password"}
                name={"password"}
              >
                <AntdPassword
                  className={classNames(
                    "__wab_instance",
                    sty.passwordInput__s1Ows
                  )}
                />
              </FormItemWrapper>
              <FormItemWrapper
                className={classNames("__wab_instance", sty.formField__vaKcp)}
                label={"Confirm Password"}
                name={"confirmPassword"}
              >
                <AntdPassword
                  className={classNames(
                    "__wab_instance",
                    sty.passwordInput__wXxH
                  )}
                />
              </FormItemWrapper>
              <AntdButton
                className={classNames("__wab_instance", sty.button)}
                submitsForm={true}
                type={"primary"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kJrKc
                  )}
                >
                  {"Sign In"}
                </div>
              </AntdButton>
            </FormWrapper>
          );
        })()}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__eUnuO)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__eaifx
          )}
        >
          {"Check your email"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "credentialsForm", "input", "button"],
  credentialsForm: ["credentialsForm", "input", "button"],
  input: ["input"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  credentialsForm: typeof FormWrapper;
  input: typeof AntdInput;
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPwForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPwForm__VariantsArgs;
    args?: PlasmicPwForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPwForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPwForm__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPwForm__ArgProps,
          internalVariantPropNames: PlasmicPwForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPwForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPwForm";
  } else {
    func.displayName = `PlasmicPwForm.${nodeName}`;
  }
  return func;
}

export const PlasmicPwForm = Object.assign(
  // Top-level PlasmicPwForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    credentialsForm: makeNodeComponent("credentialsForm"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicPwForm
    internalVariantProps: PlasmicPwForm__VariantProps,
    internalArgProps: PlasmicPwForm__ArgProps
  }
);

export default PlasmicPwForm;
/* prettier-ignore-end */
