/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: qTyITqH96yO7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicAuthFormFirst.module.css"; // plasmic-import: qTyITqH96yO7/css

createPlasmicElementProxy;

export type PlasmicAuthFormFirst__VariantMembers = {
  mode: "signIn" | "signUp" | "checkEmail" | "forgotPassword";
};
export type PlasmicAuthFormFirst__VariantsArgs = {
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "forgotPassword">;
};
type VariantPropType = keyof PlasmicAuthFormFirst__VariantsArgs;
export const PlasmicAuthFormFirst__VariantProps = new Array<VariantPropType>(
  "mode"
);

export type PlasmicAuthFormFirst__ArgsType = {
  handleSubmit?: (mode: string, credentials: any) => void;
  onCurrentModeChange?: (val: string) => void;
  setResetEmail?: string;
  handlePasswordReset?: () => void;
};
type ArgPropType = keyof PlasmicAuthFormFirst__ArgsType;
export const PlasmicAuthFormFirst__ArgProps = new Array<ArgPropType>(
  "handleSubmit",
  "onCurrentModeChange",
  "setResetEmail",
  "handlePasswordReset"
);

export type PlasmicAuthFormFirst__OverridesType = {
  root?: Flex__<"div">;
  credentialsForm?: Flex__<typeof FormWrapper>;
  emailInput?: Flex__<typeof AntdInput>;
  passwordInput?: Flex__<typeof AntdPassword>;
  forgotPasswordForm?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultAuthFormFirstProps {
  handleSubmit?: (mode: string, credentials: any) => void;
  onCurrentModeChange?: (val: string) => void;
  setResetEmail?: string;
  handlePasswordReset?: () => void;
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "forgotPassword">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAuthFormFirst__RenderFunc(props: {
  variants: PlasmicAuthFormFirst__VariantsArgs;
  args: PlasmicAuthFormFirst__ArgsType;
  overrides: PlasmicAuthFormFirst__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "credentialsForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "currentMode",
        type: "readonly",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "signIn",

        onChangeProp: "onCurrentModeChange"
      },
      {
        path: "mode",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.currentMode;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.mode
      },
      {
        path: "credentialsForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "resetEmail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "forgotPasswordForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "forgotPasswordForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "forgotPasswordForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "forgotPasswordForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "emailInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "passwordInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootmode_checkEmail]: hasVariant($state, "mode", "checkEmail"),
          [sty.rootmode_forgotPassword]: hasVariant(
            $state,
            "mode",
            "forgotPassword"
          ),
          [sty.rootmode_signIn]: hasVariant($state, "mode", "signIn"),
          [sty.rootmode_signUp]: hasVariant($state, "mode", "signUp")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__tIxYq, {
          [sty.freeBoxmode_checkEmail__tIxYqDeUt0]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__tIxYqslrP3]: hasVariant(
            $state,
            "mode",
            "signIn"
          ),
          [sty.freeBoxmode_signUp__tIxYqtobGl]: hasVariant(
            $state,
            "mode",
            "signUp"
          )
        })}
      >
        {(hasVariant($state, "mode", "forgotPassword") ? false : true)
          ? (() => {
              const child$Props = {
                className: classNames("__wab_instance", sty.credentialsForm, {
                  [sty.credentialsFormmode_checkEmail]: hasVariant(
                    $state,
                    "mode",
                    "checkEmail"
                  ),
                  [sty.credentialsFormmode_forgotPassword]: hasVariant(
                    $state,
                    "mode",
                    "forgotPassword"
                  ),
                  [sty.credentialsFormmode_signIn]: hasVariant(
                    $state,
                    "mode",
                    "signIn"
                  ),
                  [sty.credentialsFormmode_signUp]: hasVariant(
                    $state,
                    "mode",
                    "signUp"
                  )
                }),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["credentialsForm", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelCol: { span: 8, horizontalOnly: true },
                layout: "vertical",
                mode: "advanced",
                onFinish: async values => {
                  const $steps = {};

                  $steps["runHandleSubmit"] = true
                    ? (() => {
                        const actionArgs = {
                          eventRef: $props["handleSubmit"],
                          args: [
                            (() => {
                              try {
                                return $state.currentMode;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })(),
                            (() => {
                              try {
                                return $state.credentialsForm.value;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()
                          ]
                        };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runHandleSubmit"] != null &&
                    typeof $steps["runHandleSubmit"] === "object" &&
                    typeof $steps["runHandleSubmit"].then === "function"
                  ) {
                    $steps["runHandleSubmit"] = await $steps["runHandleSubmit"];
                  }

                  $steps["updateCurrentMode"] =
                    $state.currentMode === "signUp"
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["currentMode"]
                            },
                            operation: 0,
                            value: "checkEmail"
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                  if (
                    $steps["updateCurrentMode"] != null &&
                    typeof $steps["updateCurrentMode"] === "object" &&
                    typeof $steps["updateCurrentMode"].then === "function"
                  ) {
                    $steps["updateCurrentMode"] = await $steps[
                      "updateCurrentMode"
                    ];
                  }
                },
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["credentialsForm", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["credentialsForm"] = ref;
                },
                submitSlot: null,
                wrapperCol: { span: 16, horizontalOnly: true }
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "credentialsForm.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "credentialsForm.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"credentialsForm"}
                  data-plasmic-override={overrides.credentialsForm}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__e4PV
                    )}
                    label={"Email"}
                    name={"email"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7Jdgw
                      )}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.emailInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["emailInput", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "Email",
                          value: generateStateValueProp($state, [
                            "emailInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "emailInput.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"emailInput"}
                            data-plasmic-override={overrides.emailInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__huS9J
                    )}
                    label={"Password"}
                    name={"password"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox___1TQy)}
                    >
                      {(() => {
                        const child$Props = {
                          bordered: false,
                          className: classNames(
                            "__wab_instance",
                            sty.passwordInput
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["passwordInput", "value"],
                              AntdPassword_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder:
                            "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022",
                          value: generateStateValueProp($state, [
                            "passwordInput",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "passwordInput.value"
                            }
                          ],
                          [],
                          AntdPassword_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdPassword
                            data-plasmic-name={"passwordInput"}
                            data-plasmic-override={overrides.passwordInput}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </FormItemWrapper>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__xdqsu, {
                      [sty.buttonmode_signUp__xdqsUtobGl]: hasVariant(
                        $state,
                        "mode",
                        "signUp"
                      )
                    })}
                    shape={"default"}
                    size={"large"}
                    submitsForm={true}
                    type={"primary"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vNUsZ,
                        {
                          [sty.textmode_signUp__vNUsZtobGl]: hasVariant(
                            $state,
                            "mode",
                            "signUp"
                          )
                        }
                      )}
                    >
                      {hasVariant($state, "mode", "signUp")
                        ? "Sign Up"
                        : "Sign In"}
                    </div>
                  </AntdButton>
                </FormWrapper>
              );
            })()
          : null}
        {(
          hasVariant($state, "mode", "forgotPassword")
            ? true
            : (() => {
                try {
                  return $state.mode === "forgotPassword";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })()
        )
          ? (() => {
              const child$Props = {
                className: classNames(
                  "__wab_instance",
                  sty.forgotPasswordForm,
                  {
                    [sty.forgotPasswordFormmode_checkEmail]: hasVariant(
                      $state,
                      "mode",
                      "checkEmail"
                    ),
                    [sty.forgotPasswordFormmode_forgotPassword]: hasVariant(
                      $state,
                      "mode",
                      "forgotPassword"
                    ),
                    [sty.forgotPasswordFormmode_signIn]: hasVariant(
                      $state,
                      "mode",
                      "signIn"
                    ),
                    [sty.forgotPasswordFormmode_signUp]: hasVariant(
                      $state,
                      "mode",
                      "signUp"
                    )
                  }
                ),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["forgotPasswordForm", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelCol: { span: 8, horizontalOnly: true },
                layout: "vertical",
                mode: "advanced",
                onFinish: async values => {
                  const $steps = {};

                  $steps["runHandleResetPassword"] = true
                    ? (() => {
                        const actionArgs = {
                          eventRef: $props["handlePasswordReset"]
                        };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runHandleResetPassword"] != null &&
                    typeof $steps["runHandleResetPassword"] === "object" &&
                    typeof $steps["runHandleResetPassword"].then === "function"
                  ) {
                    $steps["runHandleResetPassword"] = await $steps[
                      "runHandleResetPassword"
                    ];
                  }
                },
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["forgotPasswordForm", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["forgotPasswordForm"] = ref;
                },
                submitSlot: null,
                wrapperCol: { span: 16, horizontalOnly: true }
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "forgotPasswordForm.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "forgotPasswordForm.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"forgotPasswordForm"}
                  data-plasmic-override={overrides.forgotPasswordForm}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField___5Aswl,
                      {
                        [sty.formFieldmode_forgotPassword___5Aswlu8Bjw]:
                          hasVariant($state, "mode", "forgotPassword")
                      }
                    )}
                    label={"Email"}
                    name={
                      hasVariant($state, "mode", "forgotPassword")
                        ? "email"
                        : "resetEmail"
                    }
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.input),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["input", "value"],
                            AntdInput_Helpers
                          ).apply(null, eventArgs);
                        },
                        value: generateStateValueProp($state, [
                          "input",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "input.value"
                          }
                        ],
                        [],
                        AntdInput_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdInput
                          data-plasmic-name={"input"}
                          data-plasmic-override={overrides.input}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <AntdButton
                    className={classNames(
                      "__wab_instance",
                      sty.button___9ZmZk,
                      {
                        [sty.buttonmode_forgotPassword___9ZmZku8Bjw]:
                          hasVariant($state, "mode", "forgotPassword"),
                        [sty.buttonmode_signUp___9ZmZKtobGl]: hasVariant(
                          $state,
                          "mode",
                          "signUp"
                        )
                      }
                    )}
                    submitsForm={true}
                    type={"primary"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mtWzn,
                        {
                          [sty.textmode_signUp__mtWzntobGl]: hasVariant(
                            $state,
                            "mode",
                            "signUp"
                          )
                        }
                      )}
                    >
                      {hasVariant($state, "mode", "signUp")
                        ? "Sign Up"
                        : "Sign In"}
                    </div>
                  </AntdButton>
                </FormWrapper>
              );
            })()
          : null}
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__pc60D, {
            [sty.freeBoxmode_checkEmail__pc60DDeUt0]: hasVariant(
              $state,
              "mode",
              "checkEmail"
            ),
            [sty.freeBoxmode_forgotPassword__pc60Du8Bjw]: hasVariant(
              $state,
              "mode",
              "forgotPassword"
            ),
            [sty.freeBoxmode_signIn__pc60DslrP3]: hasVariant(
              $state,
              "mode",
              "signIn"
            )
          })}
        >
          <PlasmicLink__
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link
            )}
            component={Link}
            href={(() => {
              try {
                return "https://accounts.offtoglow.com/MT3pje7t1Prbi5r4/pwresetrequest";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return `/MT3pje7t1Prbi5r4/pwresetrequest`;
                }
                throw e;
              }
            })()}
            platform={"nextjs"}
            target={"_blank"}
          >
            {"Forgot Password"}
          </PlasmicLink__>
        </Stack__>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__dKwms, {
          [sty.freeBoxmode_checkEmail__dKwmsDeUt0]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__dKwmsslrP3]: hasVariant(
            $state,
            "mode",
            "signIn"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__cAyD,
            {
              [sty.textmode_checkEmail__cAyDDeUt0]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              )
            }
          )}
        >
          {"Check your email"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "credentialsForm",
    "emailInput",
    "passwordInput",
    "forgotPasswordForm",
    "input",
    "link"
  ],
  credentialsForm: ["credentialsForm", "emailInput", "passwordInput"],
  emailInput: ["emailInput"],
  passwordInput: ["passwordInput"],
  forgotPasswordForm: ["forgotPasswordForm", "input"],
  input: ["input"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  credentialsForm: typeof FormWrapper;
  emailInput: typeof AntdInput;
  passwordInput: typeof AntdPassword;
  forgotPasswordForm: typeof FormWrapper;
  input: typeof AntdInput;
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAuthFormFirst__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAuthFormFirst__VariantsArgs;
    args?: PlasmicAuthFormFirst__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAuthFormFirst__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAuthFormFirst__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAuthFormFirst__ArgProps,
          internalVariantPropNames: PlasmicAuthFormFirst__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAuthFormFirst__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAuthFormFirst";
  } else {
    func.displayName = `PlasmicAuthFormFirst.${nodeName}`;
  }
  return func;
}

export const PlasmicAuthFormFirst = Object.assign(
  // Top-level PlasmicAuthFormFirst renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    credentialsForm: makeNodeComponent("credentialsForm"),
    emailInput: makeNodeComponent("emailInput"),
    passwordInput: makeNodeComponent("passwordInput"),
    forgotPasswordForm: makeNodeComponent("forgotPasswordForm"),
    input: makeNodeComponent("input"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicAuthFormFirst
    internalVariantProps: PlasmicAuthFormFirst__VariantProps,
    internalArgProps: PlasmicAuthFormFirst__ArgProps
  }
);

export default PlasmicAuthFormFirst;
/* prettier-ignore-end */
