/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo
// Component: ER7ouwJGwhQ1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rpSUvc8HqqQeYPehLJKGyo/projectcss
import sty from "./PlasmicAuthFormBookingsForm.module.css"; // plasmic-import: ER7ouwJGwhQ1/css

createPlasmicElementProxy;

export type PlasmicAuthFormBookingsForm__VariantMembers = {
  mode: "signIn" | "signUp" | "checkEmail" | "forgotPassword";
};
export type PlasmicAuthFormBookingsForm__VariantsArgs = {
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "forgotPassword">;
};
type VariantPropType = keyof PlasmicAuthFormBookingsForm__VariantsArgs;
export const PlasmicAuthFormBookingsForm__VariantProps =
  new Array<VariantPropType>("mode");

export type PlasmicAuthFormBookingsForm__ArgsType = {
  handleSubmit?: (mode: string, credentials: any) => void;
  onCurrentModeChange?: (val: string) => void;
  setResetEmail?: string;
  handlePasswordReset?: () => void;
};
type ArgPropType = keyof PlasmicAuthFormBookingsForm__ArgsType;
export const PlasmicAuthFormBookingsForm__ArgProps = new Array<ArgPropType>(
  "handleSubmit",
  "onCurrentModeChange",
  "setResetEmail",
  "handlePasswordReset"
);

export type PlasmicAuthFormBookingsForm__OverridesType = {
  root?: Flex__<"div">;
  credentialsForm?: Flex__<typeof FormWrapper>;
  passwordInput?: Flex__<typeof AntdPassword>;
  forgotPasswordForm?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
};

export interface DefaultAuthFormBookingsFormProps {
  handleSubmit?: (mode: string, credentials: any) => void;
  onCurrentModeChange?: (val: string) => void;
  setResetEmail?: string;
  handlePasswordReset?: () => void;
  mode?: SingleChoiceArg<"signIn" | "signUp" | "checkEmail" | "forgotPassword">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAuthFormBookingsForm__RenderFunc(props: {
  variants: PlasmicAuthFormBookingsForm__VariantsArgs;
  args: PlasmicAuthFormBookingsForm__ArgsType;
  overrides: PlasmicAuthFormBookingsForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "credentialsForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "currentMode",
        type: "readonly",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "signUp",

        onChangeProp: "onCurrentModeChange"
      },
      {
        path: "mode",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.currentMode;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.mode
      },
      {
        path: "credentialsForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "credentialsForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "resetEmail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "forgotPasswordForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "forgotPasswordForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "forgotPasswordForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "forgotPasswordForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootmode_checkEmail]: hasVariant($state, "mode", "checkEmail"),
          [sty.rootmode_forgotPassword]: hasVariant(
            $state,
            "mode",
            "forgotPassword"
          ),
          [sty.rootmode_signIn]: hasVariant($state, "mode", "signIn"),
          [sty.rootmode_signUp]: hasVariant($state, "mode", "signUp")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__mz0Ji, {
          [sty.freeBoxmode_checkEmail__mz0JiAsXrv]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__mz0Ji6A3DF]: hasVariant(
            $state,
            "mode",
            "signIn"
          ),
          [sty.freeBoxmode_signUp__mz0JiCx1E6]: hasVariant(
            $state,
            "mode",
            "signUp"
          )
        })}
      >
        {(hasVariant($state, "mode", "forgotPassword") ? false : true)
          ? (() => {
              const child$Props = {
                className: classNames("__wab_instance", sty.credentialsForm, {
                  [sty.credentialsFormmode_checkEmail]: hasVariant(
                    $state,
                    "mode",
                    "checkEmail"
                  ),
                  [sty.credentialsFormmode_forgotPassword]: hasVariant(
                    $state,
                    "mode",
                    "forgotPassword"
                  ),
                  [sty.credentialsFormmode_signIn]: hasVariant(
                    $state,
                    "mode",
                    "signIn"
                  ),
                  [sty.credentialsFormmode_signUp]: hasVariant(
                    $state,
                    "mode",
                    "signUp"
                  )
                }),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["credentialsForm", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: undefined,
                labelCol: { span: 8, horizontalOnly: true },
                layout: "horizontal",
                mode: undefined,
                onFinish: async values => {
                  const $steps = {};

                  $steps["runHandleSubmit"] = true
                    ? (() => {
                        const actionArgs = {
                          eventRef: $props["handleSubmit"],
                          args: [
                            (() => {
                              try {
                                return $state.currentMode;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })(),
                            (() => {
                              try {
                                return $state.credentialsForm.value;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()
                          ]
                        };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runHandleSubmit"] != null &&
                    typeof $steps["runHandleSubmit"] === "object" &&
                    typeof $steps["runHandleSubmit"].then === "function"
                  ) {
                    $steps["runHandleSubmit"] = await $steps["runHandleSubmit"];
                  }

                  $steps["updateCurrentMode"] =
                    $state.currentMode === "signUp"
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["currentMode"]
                            },
                            operation: 0,
                            value: "checkEmail"
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                  if (
                    $steps["updateCurrentMode"] != null &&
                    typeof $steps["updateCurrentMode"] === "object" &&
                    typeof $steps["updateCurrentMode"].then === "function"
                  ) {
                    $steps["updateCurrentMode"] = await $steps[
                      "updateCurrentMode"
                    ];
                  }
                },
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["credentialsForm", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["credentialsForm"] = ref;
                },
                wrapperCol: { span: 16, horizontalOnly: true }
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "credentialsForm.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "credentialsForm.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"credentialsForm"}
                  data-plasmic-override={overrides.credentialsForm}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__kdj34
                    )}
                    label={"Email"}
                    name={"email"}
                  >
                    <AntdInput
                      className={classNames("__wab_instance", sty.input__zGoWx)}
                    />
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__inCa
                    )}
                    label={"Password"}
                    name={"password"}
                  >
                    <AntdPassword
                      className={classNames(
                        "__wab_instance",
                        sty.passwordInput
                      )}
                    />
                  </FormItemWrapper>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__cmcNk, {
                      [sty.buttonmode_signUp__cmcNkCx1E6]: hasVariant(
                        $state,
                        "mode",
                        "signUp"
                      )
                    })}
                    shape={"default"}
                    submitsForm={true}
                    type={"primary"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6DFyN,
                        {
                          [sty.textmode_signUp___6DFyNCx1E6]: hasVariant(
                            $state,
                            "mode",
                            "signUp"
                          )
                        }
                      )}
                    >
                      {hasVariant($state, "mode", "signUp")
                        ? "Sign Up"
                        : "Sign In"}
                    </div>
                  </AntdButton>
                </FormWrapper>
              );
            })()
          : null}
        {(
          hasVariant($state, "mode", "forgotPassword")
            ? true
            : (() => {
                try {
                  return $state.mode === "forgotPassword";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })()
        )
          ? (() => {
              const child$Props = {
                className: classNames(
                  "__wab_instance",
                  sty.forgotPasswordForm,
                  {
                    [sty.forgotPasswordFormmode_checkEmail]: hasVariant(
                      $state,
                      "mode",
                      "checkEmail"
                    ),
                    [sty.forgotPasswordFormmode_forgotPassword]: hasVariant(
                      $state,
                      "mode",
                      "forgotPassword"
                    ),
                    [sty.forgotPasswordFormmode_signIn]: hasVariant(
                      $state,
                      "mode",
                      "signIn"
                    ),
                    [sty.forgotPasswordFormmode_signUp]: hasVariant(
                      $state,
                      "mode",
                      "signUp"
                    )
                  }
                ),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["forgotPasswordForm", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelCol: { span: 8, horizontalOnly: true },
                layout: "vertical",
                mode: "advanced",
                onFinish: async values => {
                  const $steps = {};

                  $steps["runHandleResetPassword"] = true
                    ? (() => {
                        const actionArgs = {
                          eventRef: $props["handlePasswordReset"]
                        };
                        return (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runHandleResetPassword"] != null &&
                    typeof $steps["runHandleResetPassword"] === "object" &&
                    typeof $steps["runHandleResetPassword"].then === "function"
                  ) {
                    $steps["runHandleResetPassword"] = await $steps[
                      "runHandleResetPassword"
                    ];
                  }
                },
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["forgotPasswordForm", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["forgotPasswordForm"] = ref;
                },
                submitSlot: null,
                wrapperCol: { span: 16, horizontalOnly: true }
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "forgotPasswordForm.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "forgotPasswordForm.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"forgotPasswordForm"}
                  data-plasmic-override={overrides.forgotPasswordForm}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__dspYs,
                      {
                        [sty.formFieldmode_forgotPassword__dspYsMq9Ik]:
                          hasVariant($state, "mode", "forgotPassword")
                      }
                    )}
                    label={"Email"}
                    name={
                      hasVariant($state, "mode", "forgotPassword")
                        ? "email"
                        : "resetEmail"
                    }
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.input),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["input", "value"],
                            AntdInput_Helpers
                          ).apply(null, eventArgs);
                        },
                        value: generateStateValueProp($state, [
                          "input",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "input.value"
                          }
                        ],
                        [],
                        AntdInput_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdInput
                          data-plasmic-name={"input"}
                          data-plasmic-override={overrides.input}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <AntdButton
                    className={classNames(
                      "__wab_instance",
                      sty.button___5OpRr,
                      {
                        [sty.buttonmode_forgotPassword___5OpRrMq9Ik]:
                          hasVariant($state, "mode", "forgotPassword"),
                        [sty.buttonmode_signUp___5OpRrCx1E6]: hasVariant(
                          $state,
                          "mode",
                          "signUp"
                        )
                      }
                    )}
                    submitsForm={true}
                    type={"primary"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oVoDg,
                        {
                          [sty.textmode_signUp__oVoDgCx1E6]: hasVariant(
                            $state,
                            "mode",
                            "signUp"
                          )
                        }
                      )}
                    >
                      {hasVariant($state, "mode", "signUp")
                        ? "Sign Up"
                        : "Sign In"}
                    </div>
                  </AntdButton>
                </FormWrapper>
              );
            })()
          : null}
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___6Ry9W, {
            [sty.freeBoxmode_checkEmail___6Ry9WasXrv]: hasVariant(
              $state,
              "mode",
              "checkEmail"
            ),
            [sty.freeBoxmode_forgotPassword___6Ry9WMq9Ik]: hasVariant(
              $state,
              "mode",
              "forgotPassword"
            ),
            [sty.freeBoxmode_signIn___6Ry9W6A3DF]: hasVariant(
              $state,
              "mode",
              "signIn"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uSMqU,
              {
                [sty.textmode_forgotPassword__uSMqUMq9Ik]: hasVariant(
                  $state,
                  "mode",
                  "forgotPassword"
                ),
                [sty.textmode_signIn__uSMqU6A3DF]: hasVariant(
                  $state,
                  "mode",
                  "signIn"
                ),
                [sty.textmode_signUp__uSMqUCx1E6]: hasVariant(
                  $state,
                  "mode",
                  "signUp"
                )
              }
            )}
            onClick={async event => {
              const $steps = {};

              $steps["updateCurrentMode"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["currentMode"]
                      },
                      operation: 0,
                      value:
                        $state.currentMode === "signIn"
                          ? "signUp"
                          : $state.currentMode === "signUp"
                          ? "signIn"
                          : "checkEmail"
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateCurrentMode"] != null &&
                typeof $steps["updateCurrentMode"] === "object" &&
                typeof $steps["updateCurrentMode"].then === "function"
              ) {
                $steps["updateCurrentMode"] = await $steps["updateCurrentMode"];
              }
            }}
          >
            {hasVariant($state, "mode", "signUp")
              ? "Already have an account? Sign In Now"
              : "Don't have an account? Sign Up Now"}
          </div>
          {(() => {
            try {
              return $state.currentMode === "signIn";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fy1J2,
                {
                  [sty.textmode_forgotPassword__fy1J2Mq9Ik]: hasVariant(
                    $state,
                    "mode",
                    "forgotPassword"
                  ),
                  [sty.textmode_signIn__fy1J26A3DF]: hasVariant(
                    $state,
                    "mode",
                    "signIn"
                  ),
                  [sty.textmode_signUp__fy1J2Cx1E6]: hasVariant(
                    $state,
                    "mode",
                    "signUp"
                  )
                }
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToPasswordReset"] = true
                  ? (() => {
                      const actionArgs = {};
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToPasswordReset"] != null &&
                  typeof $steps["goToPasswordReset"] === "object" &&
                  typeof $steps["goToPasswordReset"].then === "function"
                ) {
                  $steps["goToPasswordReset"] = await $steps[
                    "goToPasswordReset"
                  ];
                }
              }}
            >
              {hasVariant($state, "mode", "signUp")
                ? "Already have an account? Sign In Now"
                : "Forgot Password"}
            </div>
          ) : null}
        </Stack__>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__bKemL, {
          [sty.freeBoxmode_checkEmail__bKemLasXrv]: hasVariant(
            $state,
            "mode",
            "checkEmail"
          ),
          [sty.freeBoxmode_signIn__bKemL6A3DF]: hasVariant(
            $state,
            "mode",
            "signIn"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__g86O,
            {
              [sty.textmode_checkEmail__g86OAsXrv]: hasVariant(
                $state,
                "mode",
                "checkEmail"
              )
            }
          )}
        >
          {"Check your email"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "credentialsForm",
    "passwordInput",
    "forgotPasswordForm",
    "input"
  ],
  credentialsForm: ["credentialsForm", "passwordInput"],
  passwordInput: ["passwordInput"],
  forgotPasswordForm: ["forgotPasswordForm", "input"],
  input: ["input"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  credentialsForm: typeof FormWrapper;
  passwordInput: typeof AntdPassword;
  forgotPasswordForm: typeof FormWrapper;
  input: typeof AntdInput;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAuthFormBookingsForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAuthFormBookingsForm__VariantsArgs;
    args?: PlasmicAuthFormBookingsForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAuthFormBookingsForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAuthFormBookingsForm__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAuthFormBookingsForm__ArgProps,
          internalVariantPropNames: PlasmicAuthFormBookingsForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAuthFormBookingsForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAuthFormBookingsForm";
  } else {
    func.displayName = `PlasmicAuthFormBookingsForm.${nodeName}`;
  }
  return func;
}

export const PlasmicAuthFormBookingsForm = Object.assign(
  // Top-level PlasmicAuthFormBookingsForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    credentialsForm: makeNodeComponent("credentialsForm"),
    passwordInput: makeNodeComponent("passwordInput"),
    forgotPasswordForm: makeNodeComponent("forgotPasswordForm"),
    input: makeNodeComponent("input"),

    // Metadata about props expected for PlasmicAuthFormBookingsForm
    internalVariantProps: PlasmicAuthFormBookingsForm__VariantProps,
    internalArgProps: PlasmicAuthFormBookingsForm__ArgProps
  }
);

export default PlasmicAuthFormBookingsForm;
/* prettier-ignore-end */
