/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rpSUvc8HqqQeYPehLJKGyo

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";
import { AntdConfigProvider } from "@plasmicpkgs/antd5/skinny/registerConfigProvider";
import { ContentStackCredentialsProvider } from "@plasmicpkgs/plasmic-content-stack";
import { ParallaxProviderWrapper } from "@plasmicpkgs/react-scroll-parallax";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;

  antdConfigProviderProps?: Partial<
    Omit<React.ComponentProps<typeof AntdConfigProvider>, "children">
  >;

  contentStackCredentialsProviderProps?: Partial<
    Omit<
      React.ComponentProps<typeof ContentStackCredentialsProvider>,
      "children"
    >
  >;

  parallaxProviderWrapperProps?: Partial<
    Omit<React.ComponentProps<typeof ParallaxProviderWrapper>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const {
    children,
    embedCssProps,
    antdConfigProviderProps,
    contentStackCredentialsProviderProps,
    parallaxProviderWrapperProps
  } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : "/* CSS snippet */\n\n.rotate {\n    animation-name: rotator;\n    animation-duration: 60s;\n    animation-iteration-count: infinite;\n    animation-timing-function: linear;\n}\n\n@keyframes rotator {\n    from {\n        transform: rotate(0);\n    }\n    to {\n        transform: rotate(359deg);\n    }\n}"
      }
    >
      <AntdConfigProvider
        {...antdConfigProviderProps}
        borderRadius={
          antdConfigProviderProps && "borderRadius" in antdConfigProviderProps
            ? antdConfigProviderProps.borderRadius!
            : 6
        }
        colorBgBase={
          antdConfigProviderProps && "colorBgBase" in antdConfigProviderProps
            ? antdConfigProviderProps.colorBgBase!
            : "#ffffff"
        }
        colorError={
          antdConfigProviderProps && "colorError" in antdConfigProviderProps
            ? antdConfigProviderProps.colorError!
            : "#ff4d4f"
        }
        colorInfo={
          antdConfigProviderProps && "colorInfo" in antdConfigProviderProps
            ? antdConfigProviderProps.colorInfo!
            : "#1677ff"
        }
        colorPrimary={
          antdConfigProviderProps && "colorPrimary" in antdConfigProviderProps
            ? antdConfigProviderProps.colorPrimary!
            : "#1677ff"
        }
        colorSuccess={
          antdConfigProviderProps && "colorSuccess" in antdConfigProviderProps
            ? antdConfigProviderProps.colorSuccess!
            : "#52c41a"
        }
        colorWarning={
          antdConfigProviderProps && "colorWarning" in antdConfigProviderProps
            ? antdConfigProviderProps.colorWarning!
            : "#faad14"
        }
        controlHeight={
          antdConfigProviderProps && "controlHeight" in antdConfigProviderProps
            ? antdConfigProviderProps.controlHeight!
            : 32
        }
        defaultDark={
          antdConfigProviderProps && "defaultDark" in antdConfigProviderProps
            ? antdConfigProviderProps.defaultDark!
            : false
        }
        lineWidth={
          antdConfigProviderProps && "lineWidth" in antdConfigProviderProps
            ? antdConfigProviderProps.lineWidth!
            : 1
        }
        loadingText={
          antdConfigProviderProps && "loadingText" in antdConfigProviderProps
            ? antdConfigProviderProps.loadingText!
            : undefined
        }
        removeLoading={
          antdConfigProviderProps && "removeLoading" in antdConfigProviderProps
            ? antdConfigProviderProps.removeLoading!
            : undefined
        }
        sizeStep={
          antdConfigProviderProps && "sizeStep" in antdConfigProviderProps
            ? antdConfigProviderProps.sizeStep!
            : 4
        }
        sizeUnit={
          antdConfigProviderProps && "sizeUnit" in antdConfigProviderProps
            ? antdConfigProviderProps.sizeUnit!
            : 4
        }
        themeStyles={
          antdConfigProviderProps && "themeStyles" in antdConfigProviderProps
            ? antdConfigProviderProps.themeStyles!
            : true
            ? {
                fontFamily: "Inter",
                fontSize: "16px",
                fontWeight: "400",
                lineHeight: "1.5",
                color: "#222222",
                letterSpacing: "normal"
              }
            : undefined
        }
        wireframe={
          antdConfigProviderProps && "wireframe" in antdConfigProviderProps
            ? antdConfigProviderProps.wireframe!
            : false
        }
      >
        <ContentStackCredentialsProvider
          {...contentStackCredentialsProviderProps}
          accessToken={
            contentStackCredentialsProviderProps &&
            "accessToken" in contentStackCredentialsProviderProps
              ? contentStackCredentialsProviderProps.accessToken!
              : "cs5b69faf35efdebd91d08bcf4"
          }
          apiKey={
            contentStackCredentialsProviderProps &&
            "apiKey" in contentStackCredentialsProviderProps
              ? contentStackCredentialsProviderProps.apiKey!
              : "blt02f7b45378b008ee"
          }
          environment={
            contentStackCredentialsProviderProps &&
            "environment" in contentStackCredentialsProviderProps
              ? contentStackCredentialsProviderProps.environment!
              : "production"
          }
        >
          <ParallaxProviderWrapper
            {...parallaxProviderWrapperProps}
            scrollAxis={
              parallaxProviderWrapperProps &&
              "scrollAxis" in parallaxProviderWrapperProps
                ? parallaxProviderWrapperProps.scrollAxis!
                : undefined
            }
          >
            {children}
          </ParallaxProviderWrapper>
        </ContentStackCredentialsProvider>
      </AntdConfigProvider>
    </EmbedCss>
  );
}
